berty/berty

js/packages/berty-storybook/chat/Chat.tsx, js/packages/berty-storybook/chat/shared-components/Message.tsx, js/packages/hooks/Chat.tsx, js/packages/store/chat/AppMessage.ts, js/packages/store/chat/message.ts
=> feat(chat): add message acknowledgment

js/packages/go-bridge/Makefile
* fix typo in Makefile
* run `gomobile init` on each run
=> fix: {ios,android}-build on the CI

go/internal/ipfsutil/testing.go
=> fix(test): fix test timeout

js/packages/berty-storybook/main/List.tsx, js/packages/berty-storybook/settings/AboutBerty.tsx, js/packages/berty-storybook/settings/AppUpdates.tsx, js/packages/berty-storybook/settings/Bluetooth.tsx, js/packages/berty-storybook/settings/DevTools.tsx, js/packages/berty-storybook/settings/Mode.tsx, js/packages/berty-storybook/settings/Notifications.tsx, js/packages/berty-storybook/settings/TermsOfUse.tsx, js/packages/berty-storybook/shared-components/Header.tsx, js/packages/berty-storybook/shared-components/Request.tsx, js/packages/berty-storybook/shared-components/SettingsButtons.tsx
=> feat(chat): add navigation in implemented screens

js/packages/berty-storybook/main/Scan.tsx, js/packages/berty-storybook/settings/MyBertyId.tsx
=> feat(chat): turn fullscreens modals into pages

githooks/pre-commit, go.mod, go/.golangci.yml, go/cmd/berty/mini/main.go, go/cmd/berty/mini/view_group.go, go/cmd/berty/mini/view_group_incoming.go, go/cmd/berty/mini/view_group_outgoing.go, go/cmd/berty/mini/view_tabbed_groups.go, go/framework/bertybridge/bridge.go, go/framework/bertybridge/bridge_protocol.go, go/internal/banner/banner.go, go/internal/banner/banner_test.go, go/internal/banner/quote.go, go/internal/grpcutil/lazy_message.go, go/internal/grpcutil/server.go, go/internal/ipfsutil/datastore_namespaced.go, go/internal/tinder/driver.go, go/internal/tinder/driver_dht.go, go/internal/tinder/driver_mocked.go, go/internal/tinder/driver_multi.go, go/pkg/bertyprotocol/api_group.go, go/pkg/bertyprotocol/api_multimember.go, go/pkg/bertyprotocol/client_group.go, go/pkg/bertyprotocol/events.go, go/pkg/bertyprotocol/group.go, go/pkg/bertyprotocol/keystore_message_utils.go, go/pkg/bertyprotocol/store_message.go, go/pkg/bertyprotocol/store_metadata.go, go/pkg/bertytypes/group.go
This PR:
* configures more linters
* fixes linting issues
Everything looks good, but I would like a complementary review that particularly double-checks if I didn't resolve false positive issues
=> chore: configure more go linters

js/packages/berty-storybook/main/Scan.tsx, js/packages/berty-storybook/settings/Home.tsx, js/packages/berty-storybook/shared-components/Header.tsx, js/packages/berty-storybook/shared-components/SettingsButtons.tsx
=> fix(chat): align bullet point

go.mod, go.sum, go/cmd/berty/main.go, go/cmd/berty/mini/main.go, go/cmd/berty/mini/view_group.go, go/cmd/berty/mini/view_group_incoming.go, go/cmd/berty/mini/view_group_outgoing.go, go/cmd/berty/mini/view_tabbed_groups.go, go/framework/bertybridge/bridge_demo.go, go/framework/bertybridge/bridge_protocol.go, go/pkg/bertydemo/service.go, go/pkg/bertydemo/service_test.go, go/pkg/bertydemo/testing_test.go, go/pkg/bertyprotocol/api_app.go, go/pkg/bertyprotocol/api_client.go, go/pkg/bertyprotocol/api_contact.go, go/pkg/bertyprotocol/api_contactrequest.go, go/pkg/bertyprotocol/api_event.go, go/pkg/bertyprotocol/api_group.go, go/pkg/bertyprotocol/api_multimember.go, go/pkg/bertyprotocol/group_context.go, go/pkg/bertyprotocol/service.go, go/pkg/bertyprotocol/service_group.go, go/pkg/bertyprotocol/service_test.go, go/pkg/bertyprotocol/store_metadata.go, go/pkg/bertyprotocol/testing.go, js/packages/go-bridge/ios/GoBridge.m, js/packages/go-bridge/ios/GoBridge.swift
- Expose bridge protocol
- Rename Client to Service
Continues #1778 & #1790
=> feat(protocol): Expose bridge protocol

js/packages/berty-storybook/settings/AboutBerty.tsx, js/packages/berty-storybook/settings/AppUpdates.tsx, js/packages/berty-storybook/settings/Bluetooth.tsx, js/packages/berty-storybook/settings/DevTools.tsx, js/packages/berty-storybook/settings/Help.tsx, js/packages/berty-storybook/settings/Home.tsx, js/packages/berty-storybook/settings/Mode.tsx, js/packages/berty-storybook/settings/Notifications.tsx, js/packages/berty-storybook/shared-components/Header.tsx, js/packages/berty-storybook/shared-components/SettingsButtons.tsx
=> feat(chat): disable unimplemented buttons

js/packages/berty-storybook/chat/shared-components/Message.tsx
=> fix(chat): fix message border styles

js/packages/berty-app/App.tsx, js/packages/berty-app/LinkHandler.ts, js/packages/berty-app/ios/Berty/AppDelegate.m, js/packages/berty-app/ios/Berty/Info.plist, js/packages/berty-storybook/settings/MyBertyId.tsx
=> feat(chat): implement share button and deep link handling

js/packages/berty-storybook/Onboarding.tsx, js/packages/berty-storybook/chat/Chat.tsx, js/packages/berty-storybook/chat/ChatGroup.tsx, js/packages/berty-storybook/chat/ChatSettings.tsx, js/packages/berty-storybook/chat/ContactChatSettings.tsx, js/packages/berty-storybook/chat/GroupChatSettings.tsx, js/packages/berty-storybook/chat/shared-components/Message.tsx, js/packages/berty-storybook/main/CreateGroup.tsx, js/packages/berty-storybook/main/GroupRequest.tsx, js/packages/berty-storybook/main/InvalidScan.tsx, js/packages/berty-storybook/main/List.tsx, js/packages/berty-storybook/settings/AboutBerty.tsx, js/packages/berty-storybook/settings/BlockedContacts.tsx, js/packages/berty-storybook/settings/Bluetooth.tsx, js/packages/berty-storybook/settings/DevTools.tsx, js/packages/berty-storybook/settings/EditProfile.tsx, js/packages/berty-storybook/settings/Help.tsx, js/packages/berty-storybook/settings/Mode.tsx, js/packages/berty-storybook/settings/Notifications.tsx, js/packages/berty-storybook/settings/TermsOfUse.tsx, js/packages/berty-storybook/shared-components/FingerprintContent.tsx, js/packages/berty-storybook/shared-components/Header.tsx, js/packages/berty-storybook/shared-components/ProceduralCircleAvatar.tsx, js/packages/berty-storybook/shared-components/Request.tsx, js/packages/berty-storybook/shared-components/SDTSModalComponent.tsx, js/packages/berty-storybook/shared-components/SettingsButtons.tsx, js/packages/berty-storybook/shared-components/TabBar.tsx, js/packages/styles/index.tsx
=> fix(chat): fix conversation header

js/packages/berty-storybook/chat/Chat.tsx, js/packages/berty-storybook/chat/shared-components/Chat.tsx, js/packages/berty-storybook/main/List.tsx, js/packages/berty-storybook/main/Scan.tsx, js/packages/berty-storybook/shared-components/ProceduralCircleAvatar.tsx, js/packages/store/chat/AppMessage.ts, js/packages/store/chat/conversation.ts, js/packages/store/chat/message.ts
=> feat(chat): fill with samples when not enough conversations

.buildkite/pipeline.yml, go/cmd/berty/main.go, go/cmd/berty/mini/main.go, go/cmd/berty/mini/view_group.go, go/cmd/berty/mini/view_group_incoming.go, go/cmd/berty/mini/view_tabbed_groups.go
This PR configures the logger on berty mini and add some default debug
It can help to debug #1812
=> feat: add logging to berty mini

js/README.md
Instructions for installing and running debug and storybook dev environments.
Closes #1814
=> docs(js): Create readme for js subfolder

js/global.d.ts, js/package.json, js/packages/berty-app/metro.config.js, js/packages/berty-app/package.json, js/packages/berty-storybook/main/Scan.tsx, js/packages/berty-storybook/main/scan_target.svg, js/packages/berty-storybook/package.json, js/yarn.lock
- Fixes #1715
- Fixes #1834
There was a bug when `react-native-svg-transformer` tries to require `react-native/package.json` so I needed to "nohoist" it
=> Clean QR code scanner

js/packages/berty-storybook/chat/Chat.tsx, js/packages/berty-storybook/chat/ChatSettings.tsx, js/packages/berty-storybook/chat/ContactChatSettings.tsx
=> feat(chat): add contact screen

js/packages/berty-storybook/chat/Chat.tsx, js/packages/berty-storybook/package.json, js/packages/hooks/Chat.tsx, js/packages/store/chat/message.ts, js/yarn.lock
=> fix(chat): contact last seen

js/packages/berty-navigation/index.tsx, js/packages/berty-storybook/settings/Footer.tsx, js/packages/berty-storybook/shared-components/Footer.tsx
=> fix(chat): hide footer in settings subscreens

js/packages/berty-navigation/index.tsx, js/packages/berty-storybook/main/ContactRequest.tsx, js/packages/berty-storybook/main/List.tsx, js/packages/berty-storybook/main/ScanRequest.tsx, js/packages/berty-storybook/settings/Mode.tsx
=> feat(chat): contact request incoming details page

js/packages/berty-storybook/modals/AddThisContact.tsx
=> feat(chat): add this contact modal

js/packages/berty-storybook/settings/AppUpdates.tsx, js/packages/berty-storybook/settings/BlockedContacts.tsx, js/packages/berty-storybook/settings/Home.tsx, js/packages/berty-storybook/settings/TermsOfUse.tsx, js/packages/berty-storybook/shared-components/Header.tsx, js/packages/berty-storybook/shared-components/Request.tsx, js/packages/berty-storybook/shared-components/SDTSModalComponent.tsx, js/packages/berty-storybook/shared-components/SettingsButtons.tsx, js/packages/berty-storybook/shared-components/TabBar.tsx
Contributes to #1836 
This caused warnings everywhere and was a noop
=> fix(chat): remove bad usages of styles.text.family

js/packages/berty-storybook/chat/Chat.tsx, js/packages/berty-storybook/main/List.tsx, js/packages/berty-storybook/shared-components/Footer.tsx, js/packages/hooks/Chat.tsx, js/packages/store/chat/conversation.ts, js/packages/store/chat/message.ts
Fixes #1701 
This also include a small fix for the footer buttons size and another fix for the usage of FlatList in the Chat component (which caused a warning when entering a conversation)
=> Conversation thumbnail icons

js/packages/berty-storybook/settings/AboutBerty.tsx
=> feat(chat): add link to the website and contact us

js/packages/berty-storybook/chat/ChatSettings.tsx, js/packages/berty-storybook/chat/ContactChatSettings.tsx, js/packages/berty-storybook/modals/AddThisContact.tsx, js/packages/berty-storybook/shared-components/Request.tsx, js/packages/styles/index.tsx
Change the way to boldify text
=> fix(chat): text bold style

js/packages/berty-storybook/main/List.tsx, js/packages/berty-storybook/settings/Home.tsx, js/packages/store/chat/conversation.ts
=> fix(chat): sort and boldify conversations

js/packages/berty-storybook/Onboarding.tsx, js/packages/berty-storybook/modals/SendContactRequest.tsx, js/packages/store/chat/account.ts
=> Show an error modal if users tries to click deep link during onboarding

go.mod, go/cmd/berty/main.go, go/cmd/berty/mini/main.go, go/internal/handshake/handshake_util_test.go, go/internal/ipfsutil/routing.go, go/internal/ipfsutil/testing.go, go/pkg/bertyprotocol/orbitdb_utils_test.go, go/pkg/bertyprotocol/testing.go
Resovle `dnsmaddr` rendez vous peer with `github.com/multiformats/go-multiaddr-dns`
=> feat(rdvp): resolve dns maddr rendezvous point

js/packages/store/chat/conversation.ts
=> fix(chat): unset conversations reading state on app open

js/packages/berty-storybook/modals/SendContactRequest.tsx
Fixes #1853 
Also prevents the user from trying to add itself
=> fix(chat): show error modal when the user tries to add the same contact twice or to add itself

js/packages/berty-storybook/chat/ContactChatSettings.tsx, js/packages/berty-storybook/main/List.tsx, js/packages/berty-storybook/modals/AddThisContact.tsx, js/packages/berty-storybook/package.json, js/packages/berty-storybook/settings/MyBertyId.tsx, js/packages/berty-storybook/shared-components/FingerprintContent.tsx, js/packages/berty-storybook/shared-components/Request.tsx, js/packages/styles/index.tsx, js/yarn.lock
Fixes #1867 
This runs a round of sha3 on the string representation of the fake public keys, would be better to change it to the raw buffer when we plug in the real protocol
=> Sha3 fingerprints

js/packages/berty-navigation/index.tsx, js/packages/berty-storybook/main/Footer.tsx, js/packages/berty-storybook/main/ListModal.tsx, js/packages/berty-storybook/shared-components/Footer.tsx
=> fix(chat): open all tabs in main modal

js/packages/berty-navigation/index.tsx, js/packages/berty-storybook/main/ListModal.tsx
=> Fix ListModal on iOS 12

js/packages/berty-storybook/chat/shared-components/Chat.tsx
=> fix(chat): grey out on send message button

js/packages/berty-storybook/chat/ContactChatSettings.tsx, js/packages/berty-storybook/modals/AddThisContact.tsx, js/packages/berty-storybook/settings/MyBertyId.tsx, js/packages/berty-storybook/shared-components/Request.tsx, js/packages/berty-storybook/shared-components/TabBar.tsx
=> fix(chat): infos and devices in tabs bar

js/packages/berty-storybook/main/List.tsx, js/packages/berty-storybook/shared-components/Footer.tsx
=> fix(chat): padding for devices without unsafe zone

js/packages/berty-storybook/main/ListModal.tsx
Fixes https://github.com/orgs/berty/projects/48#card-36803222
=> fix(chat): swipe down on main modal go back

js/packages/grpc-bridge/protocol/handler.ts
Fixes https://github.com/orgs/berty/projects/48#card-36731231
=> fix(chat): don't crash if bridge is already started

js/packages/berty-storybook/Onboarding.tsx, js/packages/store/chat/conversation.ts, js/packages/store/chat/message.ts
- skip unimplemented onboarding pages
- really wait for the account to be initialized instead of fake 1 sec spinner in GeneratingYourKey page
- change real names in samples and add Alice Yakeys
=> Improve onboarding and samples

js/packages/berty-storybook/Onboarding.tsx
- Fix GeneratingYourKey race
- Skip app mode selection
Fixes #1917
=> Rework onboarding

js/packages/berty-storybook/chat/Chat.tsx, js/packages/berty-storybook/main/List.tsx, js/packages/berty-storybook/main/ListModal.tsx, js/packages/berty-storybook/shared-components/FromNow.tsx, js/packages/store/chat/contact.ts
=> Add from-now in requests

go.mod, go/cmd/berty/main.go, go/framework/bertybridge/bridge_demo.go, go/internal/config/berty.go, go/internal/multipeer-connectivity-transport/addr.go, go/internal/multipeer-connectivity-transport/conn.go, go/internal/multipeer-connectivity-transport/connmgr.go, go/internal/multipeer-connectivity-transport/discovery.go, go/internal/multipeer-connectivity-transport/driver/bridge.go, go/internal/multipeer-connectivity-transport/driver/mc-driver/MCManager.h, go/internal/multipeer-connectivity-transport/driver/mc-driver/MCManager.m, go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge.go, go/internal/multipeer-connectivity-transport/driver/mc-driver/mc-driver.h, go/internal/multipeer-connectivity-transport/driver/mc-driver/mc-driver.m, go/internal/multipeer-connectivity-transport/driver/other_bridge.go, go/internal/multipeer-connectivity-transport/init.go, go/internal/multipeer-connectivity-transport/listener.go, go/internal/multipeer-connectivity-transport/multiaddr/init.go, go/internal/multipeer-connectivity-transport/multiaddr/multiaddr.go, go/internal/multipeer-connectivity-transport/multiaddr/pattern.go, go/internal/multipeer-connectivity-transport/multiaddr/transcoder.go, go/internal/multipeer-connectivity-transport/transport.go, js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj
Add the multipeer connectivity transport of berty v1 to the master branch of berty
=> feat: add the multipeer connectivity transport

go/cmd/berty/main.go
=> fix: wrapping in memory datastore with a lock

go.mod, go.sum, go/cmd/berty/main.go, go/internal/discordlog/discord.go, go/internal/discordlog/discord_test.go, go/internal/discordlog/doc.go, go/pkg/bertyprotocol/orbitdb.go
* add a new `berty dev share-invite` command
* add a generic discord-based logging library
* reorganize CLI commands
* add CLI command help messages
=> feat: add an helper to share invite links on a dedicated dev discord channel

go.mod, go.sum
See https://github.com/gogo/protobuf/issues/691
=> chore: hardcode dep version protobuf@v1.3.2

.buildkite/pipeline.yml, go/config.bzl, go/repositories.bzl, go/third_party/io_bazel_rules_go/PR-2181-rebase-0.23.1.patch, js/packages/go-bridge/go.mod, tool/docker-bazel/Dockerfile, tool/docker-bazel/Makefile, tool/docker-build-go/Dockerfile, tool/docker-build-go/Makefile
- bump bazel to 3.1.0
- bump go-bridge to go 1.14.3
- update buildkite images
=> chore: bump bazel to 3.1.0

js/README.md
- Updates README in ./js root with instructions for installing app for mobile development using real protocol.
- Adds Troubleshooting section after app installation instructions.
=> docs: update readme with commands to use real protocol bridge

go/framework/bertybridge/bridge_protocol.go
Remove fslock since badger already try to lock in NewDatastore method
=> fix(ios): fix lock problem with badger

js/packages/components/main/CreateGroup.tsx, js/packages/components/modals/AddThisContact.tsx, js/packages/components/modals/DeleteAccount.tsx, js/packages/components/modals/SendContactRequest.tsx
General language cleanup in user-facing text content (see diff for changes). Should be no changes to meaning, just English language quality.
Review would be appreciated.
=> chore(chat): improve user-facing language (spelling, grammar...)

.buildkite/pipeline.yml, .github/workflows/golangci-lint.yml, go/cmd/berty/main.go, go/cmd/berty/mini/main.go, go/cmd/rdvp/main.go, go/framework/bertybridge/bridge_protocol.go, go/framework/bertybridge/bridge_test.go, go/framework/bertybridge/driver_logger.go, go/framework/bertybridge/testing_test.go, go/internal/ipfsutil/api.go, go/internal/ipfsutil/repo.go, go/internal/ipfsutil/routing.go, go/internal/multipeer-connectivity-transport/conn.go, go/internal/multipeer-connectivity-transport/connmgr.go, go/internal/multipeer-connectivity-transport/discovery.go, go/internal/multipeer-connectivity-transport/init.go, go/internal/multipeer-connectivity-transport/listener.go, go/internal/multipeer-connectivity-transport/multiaddr/init.go, go/internal/multipeer-connectivity-transport/multiaddr/multiaddr.go, go/internal/multipeer-connectivity-transport/multiaddr/transcoder.go, go/internal/multipeer-connectivity-transport/transport.go, go/internal/tinder/driver_multi.go, go/internal/tracer/tracer.go, go/pkg/bertyprotocol/api_debug.go, go/pkg/bertyprotocol/client.go, go/pkg/bertyprotocol/contact_request_manager.go, go/pkg/bertyprotocol/events_sig_checkers.go, go/pkg/bertyprotocol/tinder_swiper.go
This PR:
* configure a new GitHub action that will run golangci-lint against PR, branches, etc (no need to click on a button)
* remove golangci-lint from buildkite
* fix current lint errors
=> chore: setup golangci-lint github action

go/framework/bertybridge/bridge_protocol.go
fix request manager on mobile (wasn't enable)
=> fix: request manager on mobile

CONTRIBUTING.MD
Signed-off-by: pierreboc <31745588+pierreboc@users.noreply.github.com>
=> chore: create CONTRIBUTING.MD

js/package.json, js/packages/components/chat/ChatSettings.tsx, js/packages/components/chat/ContactChatSettings.tsx, js/packages/components/chat/GroupChatSettings.tsx, js/packages/components/main/CreateGroup.tsx, js/packages/components/main/GroupRequest.tsx, js/packages/components/package.json, js/packages/components/settings/AboutBerty.tsx, js/packages/components/settings/AppUpdates.tsx, js/packages/components/settings/BlockedContacts.tsx, js/packages/components/settings/Bluetooth.tsx, js/packages/components/settings/DevTools.tsx, js/packages/components/settings/Help.tsx, js/packages/components/settings/Home.tsx, js/packages/components/settings/IpfsWebUI.tsx, js/packages/components/settings/Mode.tsx, js/packages/components/settings/MyBertyId.tsx, js/packages/components/settings/Network.tsx, js/packages/components/settings/Notifications.tsx, js/packages/components/settings/TermsOfUse.tsx
Some components haven't been tested, but it will be easy to re-enable the bounce if we need it (`bounces={false}` ---> `bounces={true}` in vertical ScrollViews).
Closes #2000
=> fix(front): stop bouncing on views with scroll if no bounce desired

js/packages/components/Onboarding.tsx, js/packages/components/modals/DeleteAccount.tsx
Blocked by #2022 (since this isn't an urgent issue and it will be much faster to rebase, as 2022 changes yarn.lock)
Closes #1996
=> fix(front): disable autocomplete/capitalization for sensitive fields

go/framework/bertybridge/bridge_protocol.go, go/framework/bertybridge/driver_logger.go, js/packages/berty-app/App.tsx, js/packages/berty-app/index.js, js/packages/go-bridge/GoBridge.ts, js/packages/go-bridge/index.ts, js/packages/go-bridge/ios/GoBridge.m, js/packages/go-bridge/ios/GoBridge.swift, js/packages/go-bridge/ios/LoggerDriver.swift, js/packages/go-bridge/logger.ts, js/packages/go-bridge/types.ts
- Fix log type naming in console (private -> public)
- Forward `console.log` to native logger
- Improve native logger
=> feat: improve logger

js/packages/components/settings/DevTools.tsx, js/packages/hooks/message.ts, js/packages/store/chat/conversation.ts, js/packages/store/chat/message.ts
=> feat(messenger): add devtool for send messages to all contacts

go.mod, go.sum, go/pkg/bertyprotocol/orbitdb.go, go/pkg/bertyprotocol/orbitdb_signed_entry_accesscontroller.go, go/pkg/bertyprotocol/service.go, js/packages/components/Onboarding.tsx, js/packages/go-bridge/Makefile, js/packages/go-bridge/ios/GoBridge.swift, js/packages/go-bridge/types.ts, js/packages/store/protocol/client.ts
- Add orbit db tracing
- Update gobridge makefile to skip build if no go files changed
- Add tracingPrefix options to BertyBridgeOpts in react-native
=> feat: Add orbitdb tracing & improve tracing

js/packages/components/settings/DevTools.tsx
=> fix(messenger): vibration and navigate after share QR on discord

js/packages/berty-navigation/stacks.tsx, js/packages/components/main/Search.tsx
This removes the fake data but keeps the styles demo'd in #2049 and keeps search footer button disabled. 
Requesting a review so I can work from this basis while implementing functionality.
Relates to #2042
=> chore(front): setup styles for search page

js/packages/store/messenger/index.ts
missed a change during the last refactor
=> fix(messenger): whitelist messenger persistance

go/pkg/banner/quote.go
Signed-off-by: pierreboc <31745588+pierreboc@users.noreply.github.com>
=> chore(quote): adding a quote from B.Schneier

go/cmd/berty/mini/view_group.go, go/cmd/berty/mini/view_group_incoming.go, go/cmd/berty/mini/view_group_outgoing.go
=> feat(mini): /contact {accept,discard} all + pastable synopsis

go/cmd/berty/mini/view_group.go, go/cmd/berty/mini/view_group_incoming.go, go/cmd/berty/mini/view_tabbed_groups.go
=> feat(mini): unread badge

go/cmd/berty/mini/view_group.go, go/cmd/berty/mini/view_group_incoming.go, go/cmd/berty/mini/view_group_outgoing.go, go/cmd/berty/mini/view_tabbed_groups.go
=> feat(mini): added /debug {system,ipfs,group} commands

js/packages/components/settings/DevTools.tsx
=> fix(messenger): delete navigation, add vibration on send to all devtool

tool/berty-mini-local-helper/Makefile, tool/berty-mini-local-helper/README.md
=> chore: add tool/berty-mini-local-helper

go/cmd/berty/mini/main.go, go/cmd/berty/mini/view_group.go, go/cmd/berty/mini/view_group_incoming.go, go/cmd/berty/mini/view_group_outgoing.go, go/cmd/berty/mini/view_tabbed_groups.go, go/pkg/bertyprotocol/store_metadata_index.go
=> feat(mini): display names support

go/cmd/berty/main.go, go/framework/bertybridge/bridge_protocol.go, go/internal/config/berty.go
Signed-off-by: remi <remi@berty.tech>
=> feat: activate multipeer connectivity by default

go/cmd/berty/mini/view_group.go, tool/berty-mini-local-helper/Makefile
=> chore: improve berty-mini debugging

go/cmd/berty/main.go, go/cmd/berty/mini/main.go, go/framework/bertybridge/bridge_protocol.go, go/internal/ipfsutil/routing.go, go/internal/ipfsutil/testing.go, js/packages/go-bridge/ios/GoBridge.swift, js/packages/store/protocol/client.ts
Signed-off-by: remi <remi@berty.tech>
=> feat: toggle localDiscovery

go.mod, go.sum, go/cmd/berty/mini/view_group_outgoing.go
=> feat: copy share commands output to clipboard in Berty mini

.github/workflows/protobuf.yml, tool/berty-mini-local-helper/Makefile
to share QR code on term + dev channel
=> chore(berty-mini-local-helper): add 'make share-qr' tool 

.github/workflows/protobuf.yml, .gitignore, README.md, docs/Makefile, docs/gen.sum, docs/messenger/bertymessenger.swagger.json, docs/protocol/bertyprotocol.swagger.json
=> chore: generate openapi documentation

tool/berty-mini-web/Makefile, tool/berty-mini-web/README.md, tool/berty-mini-web/berty-mini
=> chore: add berty-mini-web tool

js/packages/components/main/Search.tsx
Fixes #2060 
Blocked by #2145 (uses flex util additions)
=> fix(messenger): search results margins

go/cmd/berty/mini/view_group.go
=> chore: make mini's bird tell the quote of the day

js/packages/components/modals/DeleteAccount.tsx, js/packages/components/settings/Mode.tsx
=> fix(messenger): vibrations on delete account

go/pkg/bertyprotocol/scenario_test.go, go/pkg/bertyprotocol/testing.go
Added generic helpers that:
- Create a MultiMember Group
- Send messages on all kind of groups
- Add accounts as contacts
This way we will be able to mix the different elements much more easily to create new scenarios.
Also made generic the function to launch a scenario and its test cases.
=> test: improve scenario tests

CONTRIBUTING.MD
=> docs: simplify CONTRIBUTING.md

js/packages/components/Onboarding.tsx
Prevents sequential key generation animations from happening before Create Account is clicked (this seems to have been causing the lag)
=> perf(messenger): fix onboarding anim lag

js/packages/components/main/Search.tsx
- Adds timestamps to message search result list
- Removes sticky section headers (identified in last testing session), so Contacts section header will disappear if you scroll past that section
=> feat(messenger): add timestamp to message search result

js/packages/styles/constant.ts
Reimplements a fix for initial scale size calculation.
=> fix(messenger): fix initial scaling calculation

js/packages/components/faker.js, js/packages/components/main/Home.tsx, js/packages/components/main/HomeModal.tsx, js/packages/components/settings/SystemInfo.tsx, js/packages/store/messenger/contact.js, js/packages/store/messenger/conversation.js, js/packages/store/messenger/message.js
=> fix(messenger): svg bgcolor / gen fake datas

js/packages/components/Onboarding.tsx, js/packages/components/main/Search.tsx, js/packages/eslint-config/index.js
=> fix(messenger): fix animation lag on account create click

js/packages/components/chat/ChatGroup.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/shared-components/Chat.tsx, js/packages/components/chat/shared-components/Message.tsx, js/packages/components/faker.js, js/packages/components/main/CreateGroupFinalize.tsx, js/packages/hooks/conversation.ts, js/packages/store/groups.js, js/packages/store/messenger/contact.js, js/packages/store/messenger/conversation.js
=> fix(messenger): handle group invitation message in 1to1 conv

js/packages/components/chat/ChatGroup.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/shared-components/Chat.tsx
=> fix(messenger): textinput message

go/internal/cryptoutil/cryptoutil_test.go
Adding basic unit test for cryptutil package
=> chore: adding unit tests for cryptoutil

js/packages/berty-app/ios/Berty Debug.entitlements, js/packages/berty-app/ios/Berty Staff.entitlements, js/packages/berty-app/ios/Berty Yolo.entitlements, js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj, js/packages/berty-app/ios/Berty/Berty.entitlements, js/packages/navigation/container.tsx, js/packages/navigation/stacks.tsx, js/packages/navigation/types.ts
For the universal link we have a problem, when we open a deeplink out of app and when the app is already open nothing happen, but if app is close the deeplink works.
This issue didn't come from us but from react-navigation, we post an issue and we are waiting for an answer (https://github.com/react-navigation/react-navigation/issues/8213#issuecomment-672936747)
=> fix(messenger): universal link

go/pkg/bertymessenger/api.go, go/pkg/bertymessenger/handlers.go, go/pkg/bertymessenger/service.go, go/pkg/bertymessenger/service_test.go, go/pkg/bertymessenger/util.go
included:
stuff I wanted to do:
=> messenger: improve go store

js/packages/components/main/Home.tsx, js/packages/components/shared-components/ProceduralCircleAvatar.tsx, js/packages/store/hooks.js, js/packages/web-dev-app/src/App.tsx
=> chore(messenger): conversation list UI with new store

js/packages/web-dev-app/src/App.tsx
- Fix webdev regression after fixes to 1-1 group creation were made in messenger
- Add group members addition option in webdev multimember conversation creation
Relates to #2227
=> fix(webdev): conversation retrieval and creation bugs in webdev app

js/Makefile, js/gen.sum, js/packages/components/chat/ChatGroup.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/shared-components/Chat.tsx, js/packages/components/chat/shared-components/Message.tsx, js/packages/components/main/Home.tsx, js/packages/components/settings/DevText.tsx, js/packages/components/settings/DevTools.tsx, js/packages/store/faker.js, js/packages/store/hooks.js, js/packages/store/provider.tsx
Also fixes fake messages generation and deletion
=> messenger: restore interaction list

go/pkg/bertymessenger/api.go, js/packages/components/main/CreateGroupFinalize.tsx, js/packages/store/hooks.js, js/packages/web-dev-app/src/App.tsx
Restores multimember invitation app messages at multimember creation time.
Related to #2227
=> chore(messenger): restore multimember invitation messages

api/bertymessenger.proto, docs/gen.sum, docs/messenger/bertymessenger.swagger.json, go/gen.sum, go/pkg/bertymessenger/bertymessenger.pb.go, js/gen.sum, js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/MultiMemberQR.tsx, js/packages/components/chat/MultiMemberSettings.tsx, js/packages/components/chat/index.ts, js/packages/components/modals/InvalidScan.tsx, js/packages/components/modals/ManageDeepLink.tsx, js/packages/components/modals/ManageGroupInvitation.tsx, js/packages/components/storybook.tsx, js/packages/navigation/hook.ts, js/packages/navigation/stacks.tsx, js/packages/navigation/types.ts, js/packages/store/methods.js
- restores multimember share
- restores multimember scan
- renames Group -> MultiMember
- fixes a protobuf comment
=> messenger: restore multimember share

js/packages/components/settings/DevTools.tsx, js/packages/web-dev-app/src/App.tsx
Restores send test message to all devtool (messenger + webdev app)
Relates to #2227
=> chore(messenger): restore send to all devtool

go/pkg/banner/quote.go
Following: #1829
Reffs: https://twitter.com/Snowden/status/1294979747190050818/photo/1
=> feat: Added a quote.

go/framework/bertybridge/bridge_protocol.go, js/packages/components/gates.tsx, js/packages/components/main/HomeModal.tsx, js/packages/components/main/RequestSent.tsx, js/packages/components/shared-components/Request.tsx
- closes the bridge on a bertymessenger.New error 
- fixes the outgoing request modal
- allow to delete account on irecoverable error
=> fix(messenger): close bridge on startup error

js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/main/Home.tsx, js/packages/components/main/Search.tsx, js/packages/components/settings/Home.tsx, js/packages/components/shared-components/Footer.tsx, js/packages/navigation/types.ts, js/packages/store/hooks.js
=> fix(messenger): restore and improve search

.buildkite/pipeline.yml
Should have very minor impact on the build time (but big on the usability of the machine).
=> ci: Add niceness to the buildkite.

js/packages/components/chat/shared-components/Message.tsx, js/packages/components/package.json, js/yarn.lock
=> fix(messenger): hyperlinks

js/packages/components/main/CreateGroupAddMembers.tsx, js/packages/components/main/CreateGroupFinalize.tsx, js/packages/components/main/Home.tsx, js/packages/components/main/HomeModal.tsx, js/packages/components/shared-components/Request.tsx, js/packages/store/hooks.js, js/packages/store/methods.js
- handle long contact names in outgoing requests, conversation list, request modal
- handle long member names in multimember group creation
**also:**
- remove TS syntax in store (blocks webdev build)
- fix blocked scroll in member list on multimember group create
=> fix(messenger): Handle long contact name display

js/packages/components/main/CreateGroupAddMembers.tsx
On the first screen of the create group, we have some UI issues:
- We have not a size limit for the name of the member's list
- The scroll view scroll only when we scroll on the checkbox (right of the screen)
=> fix(messenger): create group screen

go/Makefile, go/README.md, go/cmd/berty/shareinvite.go, go/gen.sum
* initial use of embedmd to have up-to-date documentation
* not yet linked to other Makefile commands, need to manually type `make doc.generate` from `go/`
=> chore: auto-update readme's usage section with embedmd

js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/shared-components/Chat.tsx
=> fix(messenger): margin and focus on conversation

js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/shared-components/Message.tsx, js/packages/components/settings/DevTools.tsx, js/packages/store/faker.js
Add Discord share confirmation alert with cancel option
**also**
Small fixes/features identified in last testing session, 2020-09-03:
- add createdDate to fake multiMembers (already working in live ones)
- add "the group" to sent invitation message
=> feat(messenger): add Discord share confirmation dialog

go.mod, go/cmd/berty/main.go, go/pkg/errcode/error.go
=> chore: display wrapped errcode stack when printing with %+v

.buildkite/pipeline.yml, .gitignore, js/.gitignore, js/package.json, js/packages/berty-app/android/app/build.gradle, js/packages/berty-app/android/app/google-services.json, js/packages/berty-app/android/app/src/main/AndroidManifest.xml, js/packages/berty-app/android/app/src/main/java/tech/berty/app/MainActivity.java, js/packages/berty-app/android/app/src/main/java/tech/berty/app/MainApplication.java, js/packages/berty-app/android/build.gradle, js/packages/berty-app/index.js, js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj, js/packages/berty-app/ios/Berty/AppDelegate.m, js/packages/berty-app/ios/Berty/GoogleService/Berty/GoogleService-Info.plist, js/packages/berty-app/ios/Berty/GoogleService/BertyDebug/GoogleService-Info.plist, js/packages/berty-app/ios/Berty/GoogleService/BertyStaff/GoogleService-Info.plist, js/packages/berty-app/ios/Berty/GoogleService/BertyYolo/GoogleService-Info.plist, js/packages/berty-app/ios/Berty/Info.plist, js/packages/berty-app/ios/Debug.xcconfig, js/packages/berty-app/ios/Podfile, js/packages/berty-app/ios/Podfile.lock, js/packages/berty-app/ios/Release.xcconfig, js/packages/berty-app/package.json, js/yarn.lock
=> feat(messenger): crashlytics and shakebugs on dev release

js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/shared-components/Chat.tsx, js/packages/components/chat/shared-components/Message.tsx, js/packages/components/modals/ManageDeepLink.tsx, js/packages/store/hooks.js, js/packages/store/methods.js, js/packages/store/provider.tsx, js/packages/web-dev-app/src/App.tsx
- restore group invitation functionality in 1-1 chat
**also**:
- fix(messenger): add missing break stmt to app reducer
- refactor(messenger): add useClient and useOneToOneContact hooks
- fix(messenger): fix encode search and replace
Related to #2227
=> chore(messenger): restore group invitation functionality in 1-1 chat

go/pkg/bertymessenger/service.go
Remove messenger context opt has it can be confusing
=> chore: remove messenger context opts

js/packages/components/chat/OneToOne.tsx, js/packages/components/main/Home.tsx, js/packages/components/main/Search.tsx, js/packages/components/settings/Home.tsx
Hotfix to remove component created in #2315 as I fix it(it currently blocks vertical swipe/scroll gestures).
=> fix: remove gesture-blocking swipe listener

go/cmd/berty/mini/view_group.go
=> fix: Fixed typo in berty mini.

go/cmd/berty/betabot/main.go, go/cmd/berty/betabot/utils.go
=> feat: beta-bot

go/README.md, go/framework/bertybridge/bridge_protocol.go, go/internal/initutil/manager.go, go/internal/initutil/node.go, go/internal/ipfsutil/http_api.go, js/Makefile, js/gen.sum
disable it by default on non-daemon commands
=> fix: allow to specify IPFS webui addr

js/packages/components/Onboarding.tsx
=> fix(messenger): prevent from swiping back to onboarding from home

go/cmd/berty/mini/view_group.go, go/pkg/bertymessenger/api.go, go/pkg/bertyprotocol/service_group.go
* return a value in BertyMessenger.SendMessage
* close stores in deactivateGroup
* removed LocalOnly while opening groups in mini
=> fix: minor fixes around group activation and deactivation + SendMessage

go/.golangci.yml, go/cmd/berty/mini.go, go/cmd/berty/mini/main.go, go/framework/bertybridge/bridge_protocol.go, go/framework/bertybridge/driver_lifecycle.go, go/internal/initutil/manager.go, go/internal/initutil/node.go, go/internal/lifecycle/manager.go, go/pkg/bertymessenger/lifecycle.go, go/pkg/bertymessenger/service.go
Add lifecycle to bertymessenger
=> feat: Add lifecycle manager to bertymessenger

go/internal/initutil/ipfs.go, go/internal/initutil/manager.go, go/internal/initutil/node.go, go/internal/ipfsutil/api.go, go/internal/ipfsutil/http_api.go
=> feat: Add (No)Announce IPFS config as flag

go/README.md, go/cmd/berty/banner.go, go/cmd/berty/daemon.go, go/cmd/berty/groupinit.go, go/cmd/berty/mini.go, go/cmd/berty/replication.go, go/cmd/berty/shareinvite.go, go/cmd/berty/systeminfo.go, go/cmd/berty/token.go, go/cmd/berty/version.go, go/cmd/rdvp/main.go
* added/updated command usages/help messages
* print usage if you try to add args on commands that don't care about args (cc @gfanton :p)
=> chore: improve flag parsing and usage

js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/shared-components/Message.tsx
- Add "contact initiated" styled message (copy message invitation wrapper; we can factor out later into 'system message wrapper' etc)
- Resize logo above multi-member invitations for visual harmony
=> feat: contact initiated styled message

go/.golangci.yml, go/Makefile, go/framework/bertybridge/internal/bridgepb/bertybridge.pb.go, go/gen.sum, go/internal/handshake/handshake.pb.go, go/internal/initutil/manager_test.go, go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge_darwin.go, go/internal/tinder/records.pb.go, go/pkg/bertymessenger/bertymessenger.pb.go, go/pkg/bertymessenger/bertymessenger.pb.gw.go, go/pkg/bertyprotocol/bertyprotocol.pb.go, go/pkg/bertyprotocol/bertyprotocol.pb.gw.go, go/pkg/bertyprotocol/bertyreplication.pb.go, go/pkg/bertyprotocol/bertyreplication.pb.gw.go, go/pkg/bertytypes/bertytypes.pb.go, go/pkg/errcode/errcode.pb.go
=> chore: configure gofumpt

go.mod, go.sum, go/cmd/berty/banner.go, go/cmd/berty/daemon.go, go/cmd/berty/mini.go, go/cmd/berty/replication.go, go/cmd/berty/shareinvite.go, go/cmd/berty/systeminfo.go, go/cmd/berty/token.go, go/internal/initutil/manager_test.go
Related with https://github.com/peterbourgon/ff/pull/67, https://github.com/peterbourgon/ff/pull/68
=> fix: support shared cli flags with different default values

go/framework/bertybridge/bridge_protocol.go, go/framework/bertybridge/bridge_test.go
=> fix: nil lifecycle manager in bridge messenger

go.sum, go/cmd/betabot/main.go, js/packages/components/main/Home.tsx, js/packages/components/modals/AddBetabot.js, js/packages/components/settings/DevTools.tsx, js/packages/store/context.tsx, js/packages/store/hooks.js, js/packages/store/provider.tsx
=> fix: betabot behaviors

js/packages/berty-app/ios/Berty.xcodeproj/project.pbxproj, js/packages/components/NotificationBody.tsx, js/packages/navigation/index.tsx
**also**:
- Adds x86 as valid architecture option for iOS Berty Debug (and only Debug)
=> feat(js): improve notification UI/UX

.gitignore, go/cmd/betabot/main.go, tool/deployments/betabot/docker-compose.yml
@clegirar, can you check that things are working as before?
I think yes, but I didn't make a full series of tests
---
@gfanton I updated the docker-compose.yml file, but I think it will conflict with some uncommited configuration
=> chore: add betabot store + various go style improvements

go/cmd/betabot/main.go, js/packages/components/modals/AddBetabot.js
Fixes some english words, add `\n` and smileys 🙂
=> fix: betabot scenario

.github/workflows/android.yml
Once yolo is known working we will remove this.
=> ci: Added fake build log for testing YOLO

go/cmd/betabot/main.go, js/packages/components/modals/AddBetabot.js
=> fix: english in betabot scenario and fix modal on small devices

.github/workflows/android.yml, .github/workflows/ios.yml, README.md, tool/build/shell/release-ios.sh
Once actions is successfull buildkite will be removed.
=> ci: Clone the ios CI on github actions.

js/packages/berty-app/App.tsx, js/packages/components/NotificationBody.tsx, js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/navigation/index.tsx, js/packages/navigation/rootRef.ts, js/packages/store/hooks.js
=> feat(messenger): notification navigate on press

go/pkg/banner/quote.go
see issue #2407
also added comments to functions and struct
Signed-off-by: Zach Sugano <zachoooo@gmail.com>
=> fix: use local time for qotd

.github/workflows/android.yml, .github/workflows/ios.yml
More info here: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target
=> chore: setup shake on forks

js/packages/berty-app/ios/Podfile.lock, js/packages/berty-app/package.json, js/packages/components/main/Home.tsx, js/packages/components/main/Scan.tsx, js/packages/components/modals/AddBetabot.js, js/packages/components/modals/DeleteAccount.tsx, js/packages/components/package.json, js/packages/components/settings/DevTools.tsx, js/packages/components/settings/Home.tsx, js/packages/components/settings/MyBertyId.tsx, js/packages/navigation/hook.ts, js/packages/navigation/index.tsx, js/packages/navigation/package.json, js/packages/navigation/stacks.tsx, js/packages/store/hooks.js, js/packages/store/provider.tsx, js/packages/storybook-mobile/package.json, js/yarn.lock
Fix some navigation freeze issues linked to nested stack `transparentModal`
Fix navigate to Onboarding after `deleteAccount`
=> fix(messenger): navigation

docs/Makefile, docs/gen.sum, go.mod, go.sum, go/Makefile, go/gen.sum, go/internal/tools/tools.go, js/Makefile, js/gen.sum, js/packages/berty-app/ios/info.yaml
Add auto semver while running xcodegen:
=> feat: add auto semver on ios

go.mod, go.sum, go/cmd/betabot/main.go
I know perf doesn't count for betabot, but I find this cleaner.
=> perf: Cleaner replay check for beta bot and fix some race condition.

.gitignore, Dockerfile, go/cmd/berty/banner.go, go/cmd/berty/daemon.go, go/cmd/berty/groupinit.go, go/cmd/berty/mini.go, go/cmd/berty/shareinvite.go, go/cmd/berty/systeminfo.go, go/cmd/berty/token.go, go/cmd/berty/version.go, go/internal/initutil/manager_test.go, tool/deployments/testbot/Makefile, tool/deployments/testbot/docker-compose.yml
* TestBot 1: https://berty.tech/id#key=CiCTp8uUnxfqlZaebiJEEt_zY-NUnHAWJl4jbGpB7rXsbxIg6_Grg-eLJ-GtqrdARnoTY35k7AI_g5AxqyFVe2elIaA&name=TestBot+1
* ![Screenshot - Manfred 2020-10-09 at 18 16 30](https://user-images.githubusercontent.com/94029/95607141-9c914580-0a5b-11eb-912b-e402fe5e2389.png)
=> chore: deploy testbot

go/pkg/bertyprotocol/store_metadata.go, go/pkg/bertyprotocol/store_metadata_index.go, go/pkg/bertyprotocol/store_metadata_test.go
Create tests for multidevices:
- TestMultiDevices_Basic
=> chore: multidevices tests

js/packages/components/chat/ContactSettings.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/OneToOneSettings.tsx, js/packages/components/main/HomeModal.tsx, js/packages/components/main/Scan.tsx, js/packages/components/modals/AddThisContact.tsx
Fixes #2272 
Signed-off-by: clegirar <clemntgirard@gmail.com
=> fix(messenger): remove requests from modal / some fixes

js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/MultiMemberSettings.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/OneToOneSettings.tsx, js/packages/components/chat/shared-components/Chat.tsx, js/packages/components/main/CreateGroupAddMembers.tsx, js/packages/components/main/CreateGroupFooter.tsx, js/packages/components/main/HomeModal.tsx, js/packages/components/shared-components/SettingsButtons.tsx
=> fix(messenger): ui-ux beta stuff

js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/OneToOne.tsx
- add sticky header and date dividers to multimember conversations
- harmonize css between 1-1 and multimember where necessary
- in 1-1 and multimember, this does **not** fix:
- wrong date on scroll to start of fake conversation
=> WIP: chore(messenger): add date dividers to multimember conversations

go/internal/initutil/orbitdb.go, go/pkg/bertyprotocol/group_context.go, go/pkg/bertyprotocol/keystore_message.go, go/pkg/bertyprotocol/keystore_message_utils_test.go, go/pkg/bertyprotocol/orbitdb.go, go/pkg/bertyprotocol/orbitdb_utils_test.go, go/pkg/bertyprotocol/store_message.go, go/pkg/bertyprotocol/store_metadata.go
Signed-off-by: d4ryl00 <d4ryl00@gmail.com>
=> chore: unexport messageKeystore

go/internal/packingutil/packing.go
Signed-off-by: Jorropo <jorropo.pgm@gmail.com>
=> chore: Fixing typo in packing.go

js/packages/components/onboarding/CreateAccount.js
=> fix(messenger): hardcode betabot URL

js/packages/components/main/Home.tsx
- increase font size
- remove "Incoming" from body text
- factor out some styles
- fix accept btn alignment
=> fix: contact requests in Home readability

go/internal/config/berty.go
Since #2450 recently added the support for one host with multiples address this is now possible.
=> chore: Adding my server TCP's address.

.github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/js.yml, .github/workflows/protobuf.yml
=> fix: reduce globing scope in ci workflow for yarn.lock listing

go/cmd/betabot/main.go
=> feat: add replies buttons for betabot

js/packages/components/main/Search.tsx
- autofocus + show keyboard on Search screen mount
- re-add Search header with navigation arrow to Home
Preview:
=> chore(messenger): Search screen autofocus and keyboard

js/packages/components/main/Home.tsx
=> fix(messenger): contact request alignment

js/Makefile, js/gen.sum
=> feat: set Android and iOS minimum versions for gomobile bind

js/packages/components/chat/shared-components/Message.tsx, js/packages/components/main/Home.tsx
- Primarily, increase text size in Home and Message components so there is nothing too small to be readable
**also**
- Fix things that weren't aligned in home Message list
- Unify avatar sizes
- Simplify some css
=> fix(messenger): increase text size and align text in Home and Message

js/packages/components/chat/MultiMemberSettings.tsx, js/packages/components/chat/shared-components/Message.tsx, js/packages/components/main/Home.tsx
Fix https://github.com/orgs/berty/projects/42#card-47349108 https://github.com/orgs/berty/projects/42#card-47342612 https://github.com/orgs/berty/projects/42#card-47342467
=> fix(messenger): in conv keep sent state only on last message

js/packages/components/NotificationProvider.tsx, js/packages/components/main/Home.tsx, js/packages/components/onboarding/SetupFinished.js, js/packages/components/settings/Home.tsx, js/packages/components/settings/Notifications.tsx, js/packages/components/shared-components/SettingsButtons.tsx
=> fix(messenger): activate devtool notifications

go.mod, go.sum, go/internal/initutil/flag.go, go/internal/initutil/ipfs.go, go/internal/initutil/manager.go, go/internal/initutil/tor_embedded.go, go/internal/initutil/tor_unembedded.go
I'm experimenting with integration of the tor transport.
**This is WIP and will not protect any IP yet, I have some others things to do first, I've done many changes in `initutil` and I don't want more conflict when someone moves bridge's init to initutil.**
=> feat: Adding parameters for go-libp2p-tor-transport

js/packages/components/main/Home.tsx
=> fix(messenger): home conv list text size and alignment

js/packages/components/chat/shared-components/Message.tsx
=> fix(messenger): user message text timestamp size

js/packages/components/chat/OneToOne.tsx
=> fix(messenger): date text style harmonization continued

js/packages/components/settings/Mode.tsx, js/packages/components/shared-components/SettingsButtons.tsx
=> fix(messenger): increase size of all super-tiny text

js/ios/Berty/LaunchScreen.storyboard
=> fix: launch screen center icon

.github/workflows/js.yml, js/.gitignore, js/Makefile, js/gen.sum
not sure what `flags` are for in the codecov config
=> chore: add coverage for /js

go/framework/bertybridge/config_android.go, js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
=> feat: set Android tempdir in go from Java getCacheDir method

docs/Makefile, docs/gen.sum, js/Makefile, js/gen.sum, tool/go.sum
* fix: restore version in systeminfo
* improve maintainability
Depends on #2555
=> chore: small makefile refactor to handle relative go.mod

go.mod, go.sum
=> fix: rendezvous streams leaks

js/package.json, js/packages/components/onboarding/SetupFinished.js, js/packages/components/settings/Home.tsx, js/packages/components/settings/Mode.tsx, js/packages/store/provider.tsx, js/yarn.lock
=> feat(messenger): settings change i18n language

js/packages/components/settings/Home.tsx
This PR is for the issue https://github.com/berty/berty/issues/2547
=> Fix: Fixed background alignment issue with profile screen

go.mod, go.sum, go/cmd/betabot/main.go
Might fixes something, mostly simpler to maintain.
=> fix(betabot): Simpler locking for betabot's store

js/packages/components/hooks.ts, js/packages/components/main/CreateGroupFinalize.tsx, js/packages/components/main/Footer.tsx, js/packages/components/main/Home.tsx, js/packages/components/modals/AddBetabot.js, js/packages/components/modals/AddThisContact.tsx, js/packages/components/onboarding/GetStarted.tsx, js/packages/components/settings/AboutBerty.tsx, js/packages/components/settings/AddContactList.js, js/packages/components/settings/DevTools.tsx, js/packages/components/settings/Help.tsx, js/packages/components/settings/Home.tsx, js/packages/components/settings/NetworkMap.js, js/packages/components/settings/SystemInfo.tsx, js/packages/store/context.tsx, js/packages/store/providerReducer.ts, js/packages/web-dev-app/src/App.tsx
Other identified warnings but not covered here:
- When displaying a notification, fixed in the lib, but no released has been made since https://github.com/robcalcroft/react-native-in-app-notification/pull/43
- When displaying search results due to a scroll view hosting a list view
=> fix: removed some dev warnings in rn client

js/packages/components/chat/shared-components/Chat.tsx
=> fix(messenger): remove send on line return

js/packages/berty-i18n/locale/en/messages.json, js/packages/components/chat/OneToOne.tsx, js/packages/components/modals/DeleteAccount.tsx, js/packages/components/settings/DevTools.tsx, js/packages/components/settings/Notifications.tsx
=> fix(messenger): add plurals and interpolation

go/pkg/bertymessenger/service.go, js/packages/berty-i18n/locale/en/messages.json, js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/shared-components/Message.tsx, js/packages/components/helpers.ts, js/packages/components/onboarding/SetupFinished.js, js/packages/components/settings/DevTools.tsx, js/packages/components/settings/Mode.tsx, js/packages/store/context.ts, js/packages/store/providerEffects.ts, js/packages/store/providerReducer.ts
=> feat(messenger): add UI message monitor metadata

js/packages/berty-i18n/locale/en/messages.json, js/packages/components/chat/MultiMemberQR.tsx
=> fix(messenger): UI screen share qr group

go/internal/initutil/ipfs.go
Blaming myself, I've forgot the peer ID in the hack.
Thx @gfanton for the help to debug.
=> fix: relay hack announce

js/packages/components/main/Home.tsx
=> fix(messenger): i18n key of no-results search

.github/workflows/protobuf.yml, docs/Makefile, docs/gen.sum, docs/messenger/bertymessenger.swagger.json, docs/protocol/bertyprotocol.swagger.json, go/Makefile, go/gen.sum, go/pkg/bertymessenger/bertymessenger.pb.gw.go, go/pkg/bertyprotocol/bertyprotocol.pb.gw.go, go/pkg/bertyprotocol/bertyreplication.pb.gw.go, tool/docker-protoc/Dockerfile, tool/docker-protoc/Makefile
Related with https://github.com/daixiang0/gci/issues/23
Addresses berty/berty#2771
=> chore: use go1.15 in bertytech/protoc:26

go/pkg/bertyprotocol/api_event.go
Signed-off-by: phanquy <phanhuynhquy@gmail.com>
GroupMessageList() and GroupMetadataList() will include 2 parts:
- List old messages in DB (via ListEvent())
- Listen new write messages + new replicated messages - via subscribe EventWrite and EventReplicateProgress event.
With new replicated messages - currently implementation based on EventReplicateProgress event. but with this event then replicating messages have not yet been joined with current log. So we lost some replicating messages that been joining.
Solution:
1. Check if a replicating is on-going then wait until EventReplicated happen to list old message ListEvent()
=> That will take a considerably time before an old message is listed
2. Call ListEvent() again when first EventReplicated happen.
So I choose (2).
=> fix: missing replicating logs

js/packages/components/chat/message/UserMessageComponents.tsx
Issue: #2763 
It will check for message length of 325 and show only 300 character along with ... and Read more.
Only showing 300 characters will support for message if length is for ex. 326, 327.
=> read more in conversation

js/packages/go-bridge/defaults.ts, js/packages/store/providerEffects.ts
=> fix(messenger): types for store providerEffect openingDaemon

.github/workflows/android.yml, .github/workflows/go.yml, .github/workflows/integration.yml, .github/workflows/ios.yml, .github/workflows/js.yml, .github/workflows/protobuf.yml, .github/workflows/push.yml, .github/workflows/release.yml
=> chore: add a check to skip CI jobs

.github/workflows/android.yml, .github/workflows/go.yml, .github/workflows/integration.yml, .github/workflows/ios.yml, .github/workflows/js.yml, .github/workflows/protobuf.yml, .github/workflows/push.yml, .github/workflows/release.yml
This reverts commit 204a55204a4e234e5058d5ffa450e030f916cfad, reversing
changes made to 0a755d12b05d186c5a029f44d468fb4a5a17fa4c.
=> Revert "Merge pull request #2793 from berty/dev/moul/skip-ci"

go/internal/initutil/ipfs.go
This reproduce what is being done with MC
=> fix: trying to use ble on an unsupported platform

js/packages/components/settings/DevTools.tsx, js/packages/store/providerEffects.ts, js/packages/store/providerReducer.ts
Fix bridge flow for support restart option on screen stream error
=> fix: store state machine

js/packages/components/onboarding/SetupFinished.js
=> fix(messenger): call handle persistent options at onboarding

js/packages/components/avatars.tsx, js/packages/components/main/CreateGroupAddMembers.tsx
Fixes https://github.com/berty/bugs/issues/118, https://github.com/berty/bugs/issues/117
=> fix(messenger): size add members item in create group

js/packages/components/chat/common.tsx
=> fix(messenger): auto correct text input

js/packages/components/modals/AddThisContact.tsx, js/packages/components/modals/ManageDeepLink.tsx, js/packages/components/modals/ManageGroupInvitation.tsx, js/packages/components/shared-components/FingerprintContent.tsx
Example of behavior https://streamable.com/z55tzk
=> feat: ui encrypted links

js/packages/berty-i18n/index.ts
=> fix: fallback when empty string

config/config.gen.json, config/config.yml, go/internal/config/config.gen.go, go/pkg/protocoltypes/config.go, js/packages/components/avatars.tsx, js/packages/components/chat/ContactSettings.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/OneToOneSettings.tsx, js/packages/components/main/Home.tsx, js/packages/components/modals/AddBot.js, js/packages/components/modals/index.ts, js/packages/components/onboarding/CreateAccount.js, js/packages/components/onboarding/SetupFinished.js, js/packages/config/global.gen.js, js/packages/navigation/stacks.tsx, js/packages/navigation/types.ts, js/packages/store/context.ts, js/packages/store/providerEffects.ts
=> fix: implem bots

js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/settings/EditProfile.tsx, js/packages/components/shared-components/KeyboardAvoidingView.tsx, js/packages/components/shared-components/StickyMusicPlayer.tsx, js/packages/messenger-app/App.tsx
=> fix: keyboard issue fix, support music player

js/packages/components/main/CreateGroupAddMembers.tsx, js/packages/components/main/CreateGroupFinalize.tsx
Fix https://github.com/orgs/berty/projects/42#card-51408038
=> fix(messenger): navigate after create group

js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/common.tsx, js/packages/components/chat/file-uploads/AddFileMenu.tsx, js/packages/components/chat/message/PictureMessage.tsx, js/packages/components/chat/message/UserMessage.tsx, js/packages/components/main/CreateGroupAddMembers.tsx, js/packages/components/main/CreateGroupFinalize.tsx, js/packages/components/main/Home.tsx, js/packages/components/main/HomeModal.tsx, js/packages/navigation/stacks.tsx, js/packages/navigation/types.ts
- Audio Recording View
- Multiple files alignments fix
-  https://github.com/berty/bugs/issues/120
- https://github.com/berty/bugs/issues/100
- https://github.com/berty/bugs/issues/147
=> feat: ui improvements

js/packages/components/modals/AddThisContact.tsx
=> fix: navigate after add this contact

.github/workflows/ios.yml, js/Makefile, js/ios/Podfile.lock, js/package.json, js/packages/components/settings/DevTools.tsx, js/packages/components/settings/Mode.tsx, js/packages/components/shared-components/DropDownPicker.tsx, js/yarn.lock
Fixes: #2627 
Build a custom dropdown picker
https://user-images.githubusercontent.com/13379067/103136784-940beb00-46eb-11eb-936b-12da954964e0.mov
=> feat: custom dropdown picker

js/packages/components/chat/MultiMemberSettings.tsx, js/packages/components/chat/file-uploads/AddFileMenu.tsx, js/packages/components/chat/file-uploads/GallerySection.tsx, js/packages/components/chat/message/AudioMessage.tsx, js/packages/components/chat/message/PictureMessage.tsx, js/packages/components/chat/message/UserMessage.tsx, js/packages/components/main/Home.tsx
Fixes:-
https://github.com/berty/bugs/issues/131
https://github.com/berty/bugs/issues/83
https://github.com/berty/bugs/issues/130
https://github.com/berty/bugs/issues/127
https://github.com/berty/bugs/issues/134
=> feat: minor ui updates

js/packages/berty-i18n/locale/en-US/messages.json, js/packages/components/chat/ContactSettings.tsx, js/packages/components/chat/ReplicateGroupSettings.tsx, js/packages/components/main/CreateGroupFinalize.tsx, js/packages/components/modals/AddThisContact.tsx, js/packages/components/modals/ManageGroupInvitation.tsx, js/packages/components/settings/MyBertyId.tsx, js/packages/components/shared-components/DropDownPicker.tsx, js/packages/components/shared-components/Request.tsx, js/packages/components/shared-components/TabBar.tsx
Fixes:
https://github.com/berty/bugs/issues/88
https://github.com/berty/bugs/issues/92
https://github.com/berty/bugs/issues/121
https://github.com/berty/bugs/issues/154
=> feat: ui fixes

js/Makefile, tool/go.mod, tool/go.sum
=> feat: reenable tor on iOS

go/internal/initutil/datastore.go
While digging an other bug I found this one, this fixes the `-store.inmem` option.
=> fix: in memory database

.github/workflows/android.yml
This is a continuation of #3010
=> fix: android build on CI with ndk22

.github/workflows/go.yml, .github/workflows/release.yml, .gitignore, .goreleaser.yml, go.mod, go.sum, go/cmd/berty/gui.go, go/cmd/berty/gui/account.go, go/cmd/berty/gui/app.go, go/cmd/berty/gui/contacts.go, go/cmd/berty/gui/conversations.go, go/cmd/berty/gui/interactions.go, go/cmd/berty/gui/main.go, go/cmd/berty/gui/mchelper.go, go/cmd/berty/gui/multimember.go, go/cmd/berty/gui/store.go, go/cmd/berty/gui/utils.go, go/cmd/berty/main.go, go/cmd/berty/noopgui.go
`berty gui --store.dir demo.d`
or
`go run -tags bertygui ./go/cmd/berty gui --store.dir otherdemo.d`
This adds 6MB to the linux binary
=> feat: bergy

js/packages/berty-i18n/locale/en-US/messages.json, js/packages/components/main/home/HomeModal.tsx, js/packages/components/modals/AddThisContact.tsx, js/packages/components/modals/InvalidScan.tsx, js/packages/components/modals/ManageDeepLink.tsx, js/packages/components/modals/ManageGroupInvitation.tsx
Fixes: https://github.com/berty/bugs/issues/44
=> feat: swipe improvement and contact already added error message

js/gen.sum, js/package.json, js/packages/components/chat/ReplicateGroupSettings.tsx, js/yarn.lock
api used does not seem to exist in new version
=> chore(messenger): remove react-native-elements

go/cmd/berty/main.go
Signed-off-by: Norman Meier <norman@berty.tech>
=> fix(cli): check argv len before access

go/pkg/bertyprotocol/services_auth_templates.go
In #3060 I accidentally removed the button click logic. Fixed in this PR.
=> fix(replication): "Connect" button click logic

go/pkg/bertyaccount/service_account.go, js/index.js, js/packages/go-bridge/defaults.ts, js/packages/go-bridge/logger.ts
- increase log verbosity, redirect console log into native logger on release
=> fix: prog panic

js/packages/components/chat/message/MessageInvitation.tsx, js/packages/components/chat/message/UserMessage.tsx, js/packages/components/chat/message/UserMessageComponents.tsx, js/packages/components/chat/message/index.tsx, js/packages/components/main/home/Conversations.tsx, js/packages/store/faker.js
=> fix(messenger): IsMine rebase fail

js/global.d.ts, js/package.json, js/packages/berty-i18n/locale/en-US/messages.json, js/packages/components/chat/message/UserMessageComponents.tsx, js/packages/components/settings/DevTools.tsx, js/packages/go-bridge/defaults.ts, js/packages/store/context.ts, js/packages/store/providerEffects.ts, js/yarn.lock
- support some new dot app domains
- fix selectable text (fix https://github.com/berty/berty/issues/2743)
- add devtools to change daemon logs format
=> fix: hyperlink dot app domains

js/packages/components/NotificationBody.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/common.tsx, js/packages/components/main/CreateGroupFinalize.tsx, js/packages/components/main/home/Requests.tsx, js/packages/components/modals/ForwardToBertyContactModal.tsx, js/packages/components/settings/DevTools.tsx, js/packages/store/context.ts, js/packages/store/provider.tsx, js/packages/store/sounds.ts
=> fix: play sound notifications depending on notif setting

js/package.json, js/packages/components/gates.tsx, js/packages/store/context.ts, js/packages/store/providerEffects.ts, js/yarn.lock
https://user-images.githubusercontent.com/33428384/108980707-429cbf80-768c-11eb-9297-f0cf7e872e08.mov
=> fix: ui stream screen

js/packages/components/main/bluetooth.ts
=> fix: network config navigation

js/packages/components/main/NetworkOptions.tsx, js/packages/components/onboarding/ChoosePreset.tsx, js/packages/components/shared-components/SettingsButtons.tsx
=> fix: responsive screens

js/packages/components/main/home/Conversations.tsx
=> fix: align conversation and desc

js/packages/components/modals/AddBot.js, js/packages/components/modals/WelcomeConfiguration.tsx
=> fix: modals positions and alignements

js/packages/berty-i18n/locale/en-US/messages.json, js/packages/components/main/CreateGroupAddMembers.tsx, js/packages/components/main/CreateGroupFinalize.tsx, js/packages/components/main/CreateGroupFooter.tsx, js/packages/components/settings/DevTools.tsx, js/packages/components/shared-components/DropDownPicker.tsx
=> fix: create group UI

js/packages/components/settings/Home.tsx, js/packages/components/shared-components/Header.tsx
=> fix: header settings harmonization

js/packages/components/chat/common.tsx, js/packages/components/chat/record/RecordComponent.tsx
=> fix: TextInput alignment / color / multiline auto expanding

js/packages/components/avatars.tsx, js/packages/components/chat/MessageList.tsx, js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/MultiMemberSettings.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/OneToOneSettings.tsx, js/packages/components/chat/common.tsx, js/packages/components/chat/message/UserMessageComponents.tsx, js/packages/components/main/CreateGroupAddMembers.tsx, js/packages/components/main/home/Conversations.tsx, js/packages/components/main/home/Footer.tsx, js/packages/components/main/home/Header.tsx, js/packages/components/settings/Home.tsx, js/packages/components/shared-components/Header.tsx, js/packages/components/shared-components/SettingsButtons.tsx
=> fix: ui create group and conversations

.github/pull_request_template.md
=> chore: fix PR template

go/internal/logutil/logutil.go
=> chore: setup logging sampler

js/global.d.ts, js/package.json, js/packages/components/main/home/Header.tsx, js/packages/components/onboarding/ChoosePreset.tsx, js/packages/components/settings/Home.tsx, js/packages/components/settings/Mode.tsx, js/packages/components/shared-components/DropDownPicker.tsx, js/yarn.lock
=> fix: new home settings

js/package.json, js/packages/components/InfosChat.tsx, js/packages/components/avatars.tsx, js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/MultiMemberSettings.tsx, js/packages/components/chat/message/MessageInvitation.tsx, js/packages/components/modals/AddThisContact.tsx, js/packages/components/modals/ManageGroupInvitation.tsx, js/yarn.lock
=> feat(messenger): default group avatars

js/ios/Podfile.lock, js/package.json, js/packages/components/chat/common.tsx, js/yarn.lock
=> fix(messenger): android footer animation

go/pkg/bertymessenger/handlers.go
=> fix(messenger): pastille ack notification

js/packages/berty-i18n/locale/en-US/messages.json, js/packages/components/settings/DevTools.tsx, js/packages/go-bridge/defaults.ts, js/packages/store/context.ts, js/packages/store/providerEffects.ts
=> feat(messenger): log filters button

js/Makefile, js/packages/components/chat/message/AudioMessage.tsx, js/packages/components/chat/record/PreviewComponent.tsx, js/packages/components/chat/record/RecordComponent.tsx, js/packages/components/chat/record/RecordingComponent.tsx, js/packages/components/chat/record/common.ts, js/packages/store/context.ts, js/packages/store/effectableCallbacks.ts, js/packages/store/providerCallbacks.ts, js/packages/store/providerEffects.ts, js/packages/store/providerReducer.ts, js/packages/store/utils.ts
=> Remove import cycles

js/Makefile, js/packages/components/NotificationBody.tsx, js/packages/components/shared-components/Card.tsx
=> Fix notif console error

js/packages/components/settings/Bluetooth.tsx, js/packages/components/shared-components/SettingsButtons.tsx
=> fix(messenger): bluetooth grey buttons

js/package.json, js/packages/components/chat/MultiMemberQR.tsx, js/packages/components/settings/Home.tsx, js/packages/components/settings/MyBertyId.tsx, js/yarn.lock
Updated QR code circle style logic.
Create a PR on upstream https://github.com/awesomejerry/react-native-qrcode-svg/pull/139
=> feat: qr code update

js/packages/components/chat/message/AudioMessage.tsx
=> fix(messenger): audio message take full screen

js/android/app/src/main/AndroidManifest.xml, js/global.d.ts, js/package.json, js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/shared-components/KeyboardAvoidingView.tsx, js/packages/components/shared-components/StickyMusicPlayer.tsx, js/yarn.lock
Fixes: https://github.com/berty/berty/issues/3161
=> fix: support android notch for KeyboardAvoidingView

.github/workflows/release.yml
=> chore: fix libgl CI install

.github/workflows/codeql-analysis.yml
=> chore: setup codeql analysis (experiment)

js/packages/store/provider.tsx
=> fix(messenger): create new account does not work

js/packages/components/main/home/Header.tsx, js/packages/components/main/home/Home.tsx, js/packages/components/settings/EditProfile.tsx
=> fix(messenger): android edit profile

js/packages/components/error.tsx
=> fix(messenger): button restart the app in duplicate in crash screen

js/packages/components/chat/MultiMemberQR.tsx
=> fix: design multimember qr

js/packages/berty-i18n/locale/en-US/messages.json, js/packages/components/chat/ReplyReactionContext.tsx, js/packages/components/chat/common.tsx, js/packages/components/chat/message/AudioMessage.tsx, js/packages/components/chat/message/FileMessage.tsx, js/packages/components/chat/message/PictureMessage.tsx, js/packages/components/chat/message/UserMessage.tsx, js/packages/components/chat/message/UserMessageComponents.tsx, js/packages/components/utils.ts
- Highlight scrollTo message
- Position fix for reaction view
- Utilize longPress to show reaction view
Note: Removed ```selectable={true}``` from UserMessageComponent as it block long press  to open Emoji popover.
=> feat: added reply and reactions to medias

js/packages/components/AttachmentImage.tsx, js/packages/components/avatars.tsx, js/packages/components/chat/MultiMemberSettings.tsx, js/packages/components/chat/OneToOneSettings.tsx, js/packages/components/chat/message/UserMessage.tsx, js/packages/components/modals/ImageView.tsx, js/packages/navigation/types.ts
=> feat: pressable avatar images

go/internal/initutil/ipfs.go, go/internal/initutil/manager.go, go/internal/ipfsutil/helpers.go, go/internal/omnisearch/rdvp.go
=> feat: add static relays as cmd argument 

js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/MultiMemberSettings.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/SharedMedias.tsx, js/packages/components/chat/message/UserMessageComponents.tsx
- EmojiBoard can be closed pressing outside of it
- Group member count fix
- Chat -> Settings -> Links UI fixes
- DeepLink navigation fix
=> fix: minor ui fixes

go/cmd/berty/daemon.go, go/cmd/berty/shareinvite.go
=> feat: display startup info on berty daemon

js/packages/components/chat/message/UserMessageComponents.tsx
=> fix: add crypto tld

js/packages/components/settings/Home.tsx, js/packages/components/shared-components/DropDownPicker.tsx
Fix https://github.com/berty/bugs/issues/272
=> fix: android dropdown picker not scrollable

js/global.d.ts, js/package.json, js/packages/components/chat/message/Popover.tsx, js/packages/components/chat/message/UserMessage.tsx, js/packages/components/utils.ts, js/tsconfig.json, js/yarn.lock
=> fix: support all emoji shown in emoji board

js/android/build.gradle, js/ios/OpenSSL-Universal-Override.podspec, js/ios/Podfile, js/ios/Podfile.lock, js/package.json, js/yarn.lock
See: https://blog.gradle.org/jcenter-shutdown
=> fix: remove jcenter (shutdown) and replace it by mavenCentral

go/pkg/bertyaccount/service_account.go
=> chore: use standard initutil.Manager's initializer

js/packages/components/chat/message/UserMessage.tsx
=> fix: group chat text color

go/pkg/bertyaccount/service_account.go, js/android/app/build.gradle, js/android/build.gradle, js/package.json, js/yarn.lock
=> chore: v8 jit

go/pkg/bertyaccount/service_account.go
=> fix: use `initutil.New` in service_account

js/android/app/build.gradle, js/ios/Podfile.lock, js/package.json, js/yarn.lock
=> fix: android white screens emoji

api/bertyaccount.proto, docs/gen.sum, go/gen.sum, go/internal/ipfsutil/helpers_test.go, go/internal/logutil/logutil.go, go/internal/logutil/logutil_test.go, go/internal/logutil/stream.go, go/pkg/bertyaccount/bertyaccount.pb.go, go/pkg/bertyaccount/blackbox_test.go, go/pkg/bertyaccount/service_account.go, go/pkg/bertyaccount/service_log.go, js/Makefile, js/gen.sum, js/packages/api/root.pb.d.ts, js/packages/api/root.pb.js, js/packages/grpc-bridge/welsh-clients.gen.ts
=> feat: add bertyaccount.LogfileList gRPC endpoint

js/packages/store/effectableCallbacks.ts, js/packages/store/utils.ts
=> feat(js): add log files to shake reports

go/framework/bertybridge/bridge.go
potentially fix background fetch crash where service account was not initialized yet.
add a protection over background fetch exec so it will return an error instead
of crashing if service account is not initialized.
=> fix: background fetch

js/ios/Podfile.lock, js/package.json, js/packages/store/services.tsx, js/yarn.lock
=> fix: bump rn-permission and fix iOS 14.5 breaking change on openAuth

js/android/app/build.gradle, js/android/app/proguard-rules.pro, js/android/app/src/main/java/tech/berty/gobridge/BertyNearbyDriver.java, js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java, js/android/app/src/main/java/tech/berty/gobridge/GoBridgePackage.java, js/android/app/src/main/java/tech/berty/gobridge/JavaPromiseBlock.java, js/android/app/src/main/java/tech/berty/gobridge/LoggerDriver.java, js/android/app/src/main/java/tech/berty/gobridge/LoggerLevel.java, js/android/app/src/main/java/tech/berty/gobridge/bledriver/Advertiser.java, js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleDriver.java, js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleInterface.java, js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleQueue.java, js/android/app/src/main/java/tech/berty/gobridge/bledriver/DeviceManager.java, js/android/app/src/main/java/tech/berty/gobridge/bledriver/GattServer.java, js/android/app/src/main/java/tech/berty/gobridge/bledriver/GattServerCallback.java, js/android/app/src/main/java/tech/berty/gobridge/bledriver/Peer.java, js/android/app/src/main/java/tech/berty/gobridge/bledriver/PeerDevice.java, js/android/app/src/main/java/tech/berty/gobridge/bledriver/PeerManager.java, js/android/build.gradle
=> feat: make android project releasable

js/packages/components/chat/MessageList.tsx
**Issues**
1. Reply Options is not shown in betabot chat view  due to error: ```[Error: invalid wire type 4 at offset 5]```
2. Send date is not shown in betabots due to ```nextMessage``` is the ```inte``` with ```payload.options``` which is quick reply options.
**Solution**
I have filtered out the message which have ```payload.options``` to fix send data. And for reply option; extract the last message which has ```payload.options``` and use it for quick reply options
**Questions**
1. Was adding quick reply options ```payload.options``` in messages is intentional or bug?  
2. Instead of extracting payload.options Can we fix the above error?
=> fix: betabot send date and quick reply options

js/packages/components/onboarding/SetupFinished.js
=> fix: show confetti when 'Start using Berty' button pressed

js/android/app/src/main/AndroidManifest.xml, js/package.json, js/packages/components/chat/record/RecordComponent.tsx, js/yarn.lock
App crash due to error from `react-native-audio-toolkit` package
PR created: https://github.com/react-native-audio-toolkit/react-native-audio-toolkit/pull/264
=> fix: android recording error

js/packages/berty-i18n/locale/en-US/messages.json, js/packages/berty-i18n/locale/languages.js, js/packages/components/onboarding/ChoosePreset.tsx, js/packages/components/settings/Home.tsx, js/packages/navigation/stacks.tsx, js/packages/store/providerReducer.ts
=> fix: wording and lock preset screen onboarding

go/cmd/betabot/main.go
=> fix: betabot waiting time before interact

go/pkg/bertymessenger/service_test.go, js/packages/berty-i18n/locale/en-US/messages.json, js/packages/berty-i18n/locale/fr-FR/messages.json, js/packages/components/onboarding/SetupFinished.js, js/packages/components/settings/Bluetooth.tsx
=> feat: add Bluetooth permission request explanation in settings

js/android/app/build.gradle, js/android/build.gradle, js/patches/react-native+0.63.4.patch
=> fix: android build on yolo

.github/workflows/android.yml, js/android/app/build.gradle, js/android/build.gradle
=> feat: add generated version code and name in gradle

go.mod, go.sum
=> fix(android): align atomic int64s

js/packages/components/settings/AppUpdates.tsx
=> fix: add current version in updates screen

go/pkg/bertymessenger/api.go, go/pkg/bertymessenger/db.go, go/pkg/bertymessenger/db_test.go, go/pkg/bertymessenger/service.go, js/android/app/src/main/AndroidManifest.xml, js/global.d.ts, js/ios/Podfile.lock, js/package.json, js/packages/berty-i18n/locale/en-US/messages.json, js/packages/components/helpers.ts, js/packages/components/main/home/MultiAccount.tsx, js/packages/components/onboarding/CreateAccount.js, js/packages/components/settings/Mode.tsx, js/packages/store/providerEffects.ts, js/packages/store/services.tsx, js/yarn.lock
=> fix: android export account

js/packages/berty-i18n/locale/en-US/messages.json, js/packages/berty-i18n/locale/fr-FR/messages.json
=> chore: update android prominent disclosure to comply with Play Store rules

api/bertyaccount.proto, docs/apis/messengertypes.md, docs/apis/messengertypes.swagger.json, docs/gen.sum, go/gen.sum, go/pkg/bertyaccount/bertyaccount.pb.go, go/pkg/bertyaccount/blackbox_test.go, go/pkg/bertyaccount/service.go, go/pkg/bertyaccount/service_account.go, go/pkg/bertyaccount/service_grpc.go, js/gen.sum, js/packages/api/root.pb.d.ts, js/packages/api/root.pb.js, js/packages/grpc-bridge/welsh-clients.gen.ts
=> feat: add BertyAccount.ImportWithProgress alternative endpoint

js/ios/Podfile.lock, js/packages/store/services.tsx, js/yarn.lock
=> fix: remove inappbrowser hack

go/internal/logutil/logutil.go
=> fix: tyber hang

api/bertyaccount.proto
Improved the ImportAccount with progress comment.
=> docs: update bertyaccount.proto

api/bertyaccount.proto, docs/gen.sum, go/gen.sum, go/pkg/bertyaccount/bertyaccount.pb.go, js/gen.sum
=> chore: small .proto fix + regenerate

js/packages/components/avatars.tsx, js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/MultiMemberSettings.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/message/MessageSystemWrapper.tsx, js/packages/components/chat/message/QuickReplyOptions.tsx, js/packages/components/chat/message/UserMessageComponents.tsx, js/packages/components/main/home/Conversations.tsx, js/packages/components/main/home/Header.tsx, js/packages/components/main/home/Home.tsx, js/packages/components/main/home/Search.tsx, js/packages/components/settings/Home.tsx, js/packages/components/shared-components/DropDownPicker.tsx, js/packages/components/shared-components/HintBody.js, js/packages/store/context.ts, js/packages/store/hooks.ts
=> fix: quick fixes

js/packages/components/main/Permissions.tsx
=> fix: permission ui on ipad

js/packages/store/effectableCallbacks.ts, js/packages/store/providerCallbacks.ts
=> fix: call ImportAccountWithProgress

go/pkg/bertyaccount/service_account.go, go/pkg/bertyaccount/service_account_test.go
=> fix: sanitize check multi addr for network config

go/pkg/bertyaccount/service_account_test.go, js/package.json, js/packages/berty-i18n/locale/en-US/messages.json, js/packages/components/NotificationProvider.tsx, js/packages/components/helpers.ts, js/packages/components/notifications/Basic.tsx, js/packages/components/onboarding/CreateAccount.js, js/packages/components/settings/Bluetooth.tsx, js/packages/components/settings/DevTools.tsx, js/packages/components/settings/Mode.tsx, js/packages/components/settings/ServicesAuth.tsx, js/packages/components/shared-components/SettingsButtons.tsx, js/packages/store/providerReducer.ts, js/yarn.lock
=> fix: front network config

js/package.json, js/packages/components/chat/common.tsx, js/packages/components/main/NetworkOptions.tsx, js/packages/components/shared-components/DropDownPicker.tsx, js/packages/components/shared-components/Header.tsx, js/yarn.lock
=> fix: kanban fixes

js/packages/components/shared-components/Request.tsx, js/packages/components/shared-components/SettingsButtons.tsx, js/packages/components/shared-components/Toggle.tsx
=> feat: custom toggle component

js/packages/components/chat/MessageList.tsx, js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/OneToOne.tsx, js/packages/components/chat/common.tsx, js/packages/components/settings/ServicesAuth.tsx
=> fix: keyboard avoiding and persistent input values

js/packages/components/main/home/Conversations.tsx, js/packages/components/main/home/Header.tsx, js/packages/components/main/home/Home.tsx, js/packages/components/main/home/Requests.tsx, js/packages/components/main/home/UnreadCount.tsx
=> fix: UI when we have requests and no requests

js/packages/components/main/home/Home.tsx, js/packages/components/settings/MyBertyId.tsx, js/packages/components/shared-components/TabBar.tsx
=> fix: qr size was cut on large screen

js/packages/components/chat/record/RecordComponent.tsx
=> fix: ios permission mic

go/internal/messengerdb/db.go, go/internal/messengerdb/db_test.go, go/pkg/bertymessenger/api.go, go/pkg/bertymessenger/service.go, go/pkg/bertymessenger/service_test.go, js/gen.sum, js/ios/Podfile.lock, js/packages/components/chat/MessageList.tsx
db: GetAllConversations() was returning multiple entries for a single conversation
app: lazy loading of messages on conversation opening and logic welcome banner
messenger: subscribe to groups after creating/joining groups
=> fix: conversation related issues

go/Makefile, go/gen.sum
see https://github.com/golang/go/issues/49138
hotfix until apple fix this
=> fix: sigabrt on macos monterey

js/Makefile, js/fix-types.sh, js/gen.sum, js/global.d.ts, js/package.json, js/packages/go-bridge/logger.ts, js/packages/grpc-bridge/gen-clients.js, js/packages/grpc-bridge/welsh-clients.gen.ts, js/packages/navigation/hook.ts, js/packages/store/effectableCallbacks.ts, js/packages/store/hooks.ts, js/packages/store/providerCallbacks.ts, js/packages/styles/map-declaration.ts, js/tsconfig.json, js/yarn.lock
This enables type-checking on the CI for packages/store and it's imports
=> Enable type-checking for js/packages/store

js/android/app/src/main/java/tech/berty/android/MainActivity.java
react-native-gesture-handler does not trigger callbacks without those configuration changes
fix #3648
=> fix: microphone button on Android

js/packages/components/chat/message/AudioMessage.tsx, js/packages/components/chat/message/UserMessage.tsx
Implemented the new design for audio messages
=> Audio message

.crowdin.yml
=> chore: update crowdin config

js/packages/components/avatars.tsx, js/packages/components/main/home/Header.tsx
Notification badge was behind the avatar
=> fix: notification badge below the avatar

go/pkg/bertyprotocol/api_push.go, go/pkg/bertyprotocol/api_replication.go, go/pkg/bertyprotocol/api_services_auth.go
- fixed grpc tls config
- remove per rpc credentials on grpc push client
=> fix: berty services

.github/workflows/go.yml
=> chore(ci): test on mac

.github/workflows/android.yml, .github/workflows/go.yml, .github/workflows/integration.yml, .github/workflows/ios.yml, .github/workflows/js.yml, .github/workflows/protobuf.yml, .github/workflows/release.yml
=> chore: use secrets to bump cache version suffix

js/packages/components/chat/message/AudioMessage.tsx, js/packages/components/shared-components/StickyMusicPlayer.tsx
play/pause player + hide player in chat views
=> fix: play/pause player + hide player in chat views

js/packages/components/avatars.tsx, js/packages/components/settings/EditProfile.tsx
remove avatar opacity in edit profile view
=> fix: remove avatar opacity

.github/workflows/ios.yml, js/ios/.gitignore, js/packages/scripts/extract-pods-hashes.js, js/packages/scripts/restore-pods-hashes.js
this will prevent merging js bump PRs without updating the deps native part
=> fix(ci): re-enable checking Podfile.lock sync

go/internal/bertylinks/links.go, go/internal/messengerpayloads/handlers.go, go/pkg/bertymessenger/service_post_actions.go, go/pkg/messengertypes/links.go, js/android/app/src/main/java/tech/berty/notification/NotificationService.java, js/ios/Berty/AppDelegate.m, js/ios/NotificationService/NotificationService.swift, js/ios/Podfile.lock, js/packages/components/NotificationProvider.tsx, js/packages/components/chat/common.tsx, js/packages/components/modals/ManageDeepLink.tsx, js/packages/components/settings/Home.tsx, js/packages/messenger-app/App.tsx, js/packages/navigation/stacks.tsx, js/packages/store/context.ts, js/packages/store/provider.tsx, js/packages/store/providerEffects.ts, js/packages/store/types.ts
=> feat: front logic push notif

.crowdin.yml, go/localization/locales/en-US/localization.json
format based on i18next: https://www.i18next.com/translation-function/essentials
=> feat: add crowdin localization for golang

.github/workflows/integration.yml
=> test: disable periodic prod integration test on the CI

js/package.json, js/packages/components/modals/ThemeColorName.tsx, js/packages/components/settings/Home.tsx, js/packages/components/settings/ThemeEditor.tsx, js/packages/redux/persistStorage.ts, js/packages/redux/store.ts, js/packages/store/context.ts, js/packages/store/hooks.ts, js/packages/store/providerEffects.ts, js/packages/store/types.ts, js/yarn.lock
First step before using redux for the theme
=> fix: fix dark theme mode + add redux persist

js/packages/components/main/Permissions.tsx, js/packages/navigation/types.ts
this should fix "navigation after perms" problems
=> fix: permissions onComplete freeze

js/ios/Berty/AppDelegate.m
=> fix: deeplink interaction on background push notif

js/packages/components/settings/ThemeEditor.tsx
=> fix: import theme

go/pkg/bertyaccount/service_account.go, js/Makefile, js/packages/components/NotificationProvider.tsx
=> fix: use i18n variables for front push notif

js/ios/Podfile.lock, js/packages/components/onboarding/CreateAccount.tsx
* Link device was not working and is not currently implemented, and has been removed
* More info wasn't working either, and has been removed
* Advanced in the dropdown should be Import
* We had issue with alignment in the info box at the bottom, I removed the info icon
=> fix: onboarding create account name screen

js/packages/components/onboarding/CreateAccount.tsx, js/packages/store/context.ts
=> fix: apply OS language

js/packages/components/settings/ThemeEditor.tsx, js/packages/navigation/stacks.tsx
=> feat: navigation bump at the GetStarted screen

js/ios/Podfile.lock, js/packages/components/NotificationProvider.tsx, js/packages/components/chat/ContactSettings.tsx, js/packages/components/chat/MultiMemberSettings.tsx, js/packages/components/chat/OneToOneSettings.tsx, js/packages/components/notifications/ContactRequestReceived.tsx, js/packages/components/notifications/ContactRequestSent.tsx, js/packages/components/notifications/MessageReceived.tsx
Fix
https://github.com/orgs/berty/projects/42#card-74500776
https://github.com/orgs/berty/projects/42#card-74497157
https://github.com/orgs/berty/projects/42#card-72898314
=> fix: reorg conversation settings and reset navigation after onPress in-app notification

js/packages/components/main/home/MultiAccount.tsx, js/packages/store/context.ts, js/packages/styles/DarkLF-theme.json
=> fix: add LF dark theme in default collection theme

js/packages/components/main/home/Header.tsx
Signed-off-by: Xavier Le Cunff <xavier.le-cunff@azot.dev>
=> fix: add version badge to Berty icon

js/packages/components/settings/Home.tsx
Fix https://github.com/orgs/berty/projects/42#card-74281369
=> fix: add display name in qr profile

js/packages/berty-i18n/locale/en-US/messages.json, js/packages/components/chat/message/UserMessageComponents.tsx
=> fix: can collapse long message after click on read more

js/packages/components/chat/MultiMemberSettings.tsx, js/packages/components/shared-components/SettingsButtons.tsx
Fix https://github.com/orgs/berty/projects/42#card-74704114
=> fix: add dropdown to members list in multimember conv

js/packages/berty-i18n/locale/en-US/messages.json, js/packages/components/chat/footer/ChatFooter.tsx, js/packages/components/main/Permissions.tsx, js/packages/components/main/home/Home.tsx, js/packages/components/onboarding/AdvancedSettings.tsx, js/packages/components/onboarding/CreateAccountBox.tsx, js/packages/navigation/types.ts, js/packages/rnutil/checkPermissions.ts
Fix https://github.com/orgs/berty/projects/42#card-74768646 https://github.com/orgs/berty/projects/42#card-74198474
=> fix: ask permissions for push and proximity transport

js/packages/components/chat/MultiMembersSettingsAddMembers.tsx, js/packages/components/chat/footer/ChatFooter.tsx, js/packages/components/chat/footer/file-uploads/AddFileMenu.tsx, js/packages/components/chat/footer/record/RecordComponent.tsx, js/packages/components/chat/message/QuickReplyOptions.tsx, js/packages/store/provider.tsx, js/packages/store/providerCallbacks.ts
=> feat: optimistic interactions

js/packages/berty-i18n/locale/en-US/messages.json, js/packages/components/onboarding/AdvancedSettings.tsx
Fix https://github.com/orgs/berty/projects/42#card-74847594
https://user-images.githubusercontent.com/33428384/146270276-03d5c6c9-3b60-41d4-b721-eb974fea78d2.mp4
=> fix: apply button in advanced settings as float button

js/packages/components/main/Scan.tsx
QR code gets hidden after a QR code scanning
QR codes can successfully be scanned several times
=> fix: pause QR code scanner

js/packages/components/settings/Roadmap.tsx
Fix https://github.com/orgs/berty/projects/42#card-74863830
=> fix: roadmap link

js/packages/components/chat/MultiMemberQR.tsx, js/packages/components/settings/MyBertyId.tsx, js/packages/store/hooks.ts
Signed-off-by: Xavier <lecunffxavier@gmail.com>
=> fix: display qr code in right size on ipads

js/packages/berty-i18n/locale/en-US/messages.json, js/packages/berty-i18n/locale/fr-FR/messages.json
Fix https://github.com/orgs/berty/projects/42#card-74892976
=> fix: description error screens

js/packages/components/chat/MultiMemberSettings.tsx
Fix https://github.com/orgs/berty/projects/42#card-74704156
=> fix: add qr in multimember settings

js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java
=> fix: disable Android Nearby driver

js/packages/components/settings/MyBertyId.tsx
=> fix: my berty id ui

js/packages/components/shared-components/WebViews.tsx
Fix https://github.com/orgs/berty/projects/42#card-75000180
=> fix: crash on android webviews screens cause blurview

config/config.yml
=> chore: update welcomebot addr

go/internal/multipeer-connectivity-driver/driver/cgo_bridge.go, js/ios/Podfile.lock, js/packages/components/main/Permissions.tsx
Fix https://github.com/orgs/berty/projects/42#card-74198489
=> fix: properly handle denied perms

.github/workflows/ios.yml, .github/workflows/mac-runner-matrix-builder.js
=> chore: randomly choose a mac builder

js/packages/components/main/home/Conversations.tsx
transform into pure components and set rigid typing
=> chore: refactor conversations list

js/packages/components/chat/MultiMember.tsx, js/packages/components/chat/OneToOne.tsx
Signed-off-by: Xavier <lecunffxavier@gmail.com>
=> fix: remove footer conversation excessive padding

go/internal/logutil/logutil.go
=> chore: increase ipfs debugging verbosity

js/ios/info.yaml, js/packages/berty-i18n/locale/en-US/messages.json, js/packages/berty-i18n/locale/fr-FR/messages.json
Signed-off-by: Xavier Le Cunff <xavier.le-cunff@azot.dev>
=> fix: change camera permission text in english and french

js/packages/berty-i18n/locale/en-US/messages.json, js/packages/berty-i18n/locale/fr-FR/messages.json, js/packages/components/modals/ThemeColorName.tsx, js/packages/components/settings/Mode.tsx, js/packages/components/settings/ThemeEditor.tsx, js/packages/redux/reducers/theme.reducer.ts, js/packages/redux/store.ts, js/packages/store/context.ts, js/packages/store/hooks.ts, js/packages/store/providerEffects.ts, js/packages/store/types.ts
Signed-off-by: Xavier Le Cunff <xavier.le-cunff@azot.dev>
=> feat: move theme to redux store

js/packages/berty-i18n/locale/en-US/messages.json, js/packages/berty-i18n/locale/fr-FR/messages.json, js/packages/components/chat/footer/ChatFooter.tsx, js/packages/components/chat/footer/ChatTextInput.tsx, js/packages/components/chat/footer/emojis/EmojiBanner.tsx, js/packages/components/chat/footer/record/RecordComponent.tsx, js/packages/components/main/home/Conversations.tsx, js/packages/components/main/home/Header.tsx, js/packages/components/main/home/Home.tsx, js/packages/components/shared-components/DropDownPicker.tsx, js/packages/components/utils.ts, js/packages/redux/reducers/chatInputsVolatile.reducer.ts, js/packages/redux/reducers/theme.reducer.ts, js/packages/styles/types.ts, js/yarn.lock
- a suggestion modal appears when typing an emoji shortcode (eg: :wa ve: without space :))
- shortcode in text inputs are automatically replaced by the corresponding emoji
- theme is now typed
- blue offset in home on IOS is removed
- chat buttons are aligned with the input
=> feat: add emoji suggestion modal

go/internal/tinder/watchdogs_discoverer.go, tool/compose-integration/docker-compose.yml
- fix integration test
- speed up integration test
- add a log when a peer is found but was filtered
=> fix: improve and fix integration test

.github/workflows/android.yml
Signed-off-by: Luís Ferreira <contact@lsferreira.net>
=> chore(deps): bump bundletool from 1.2.0 to 1.8.2

js/packages/components/main/CreateGroupFinalize.tsx, js/packages/components/main/CreateGroupFooter.tsx, js/packages/store/methods.ts, js/packages/store/types.gen.ts
=> feat: add spinner at group creation

go/pkg/bertyreplication/services_replication.go
fix multiple subscribe to odb store
=> fix: remove multiple subscribe

js/ios/Podfile.lock, js/packages/components/chat/EnableNotificationsButton.tsx, js/packages/components/chat/MultiMemberSettings.tsx, js/packages/components/chat/footer/ChatTextInput.tsx
=> fix: front bug fixes for release

js/packages/components/chat/MultiMemberQR.tsx
=> fix: share qr in multimember qr screen

.crowdin.yml
Signed-off-by: Manfred Touron <94029+moul@users.noreply.github.com>
=> chore: fix crowdin config

js/ios/berty.yaml
=> fix: remove apex localization import to app

go.mod, go.sum, go/internal/accountutils/utils.go, go/internal/initutil/datastore.go, go/internal/initutil/ipfs.go, go/internal/initutil/node.go, go/internal/ipfsutil/repo.go, go/pkg/bertyaccount/service.go, go/pkg/bertyaccount/service_account.go, go/pkg/bertyaccount/service_storage.go, go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go, go/pkg/bertyprotocol/orbitdb_test.go, go/pkg/bertypush/push_opener.go
Use patched repo of berty.tech/go-ipfs-repo-encrypted which fixes a crash when iOS app goes in background mode.
depends on https://github.com/berty/go-ipfs-repo-encrypted/pull/22
=> fix: ios background crash

js/android/app/src/main/java/tech/berty/android/MainActivity.java, js/android/app/src/main/java/tech/berty/android/MainApplication.java, js/android/settings.gradle, js/gen.sum, js/ios/Berty/AppDelegate.h, js/ios/Berty/AppDelegate.m, js/ios/Podfile, js/ios/Podfile.lock, js/ios/berty.yaml, js/package.json, js/packages/berty-i18n/locale/en-US/messages.json, js/packages/berty-i18n/locale/fr-FR/messages.json, js/packages/components/settings/Home.tsx, js/packages/store/gen-type-utils.js, js/packages/store/types.gen.ts, js/yarn.lock
Implement a submit button to send bug report via email, using MailComposer expo module.
=> feat: setup Expo + submit button for bug reporting

js/packages/components/chat/EnableNotificationsButton.tsx
I have implemented a bad behavior of render on this component, and it broke on iOS
=> fix: push notif button

.github/workflows/monitor-runners.yml, .github/workflows/ssh-runner.yml, .github/workflows/utils/get-selfhosted-runner-status.js
=> ci: multiple fixes

.github/workflows/monitor-runners.yml
=> ci: small bash fix

go/internal/ipfsutil/pubsub_monitor.go, go/pkg/bertyprotocol/api_group.go, js/packages/components/chat/message/MessageMonitorMetadata.tsx
=> chore: replaced leaved -> left everywhere

.goreleaser.yml
=> chore: configure goreleaser to publish various OS and archs

.github/workflows/release.yml
=> chore: bump goreleaser's golang version

.github/workflows/monitor-runners.yml
=> ci: monitor runner ci job detailed output

.github/workflows/ios.yml, .github/workflows/release.yml
=> fix(ci): fix semantic-release output filtering

.github/workflows/release.yml
=> fix(ci): unshallow git before calling goreleaser

.github/workflows/utils/.goreleaser.darwin.yml, .github/workflows/utils/.goreleaser.linux.yml, .github/workflows/utils/.goreleaser.windows.yml
=> fix(ci): fix goreleaser config for darwin

go/internal/proximitytransport/ringBuffer_map.go
=> fix: double Unlock in ProximityTransport

.github/workflows/ssh-runner.yml
=> ci: install emacs and remove timeout from ssh job

js/packages/components/chat/MultiMemberQR.tsx, js/packages/components/chat/SharedMedias.tsx, js/packages/components/main/Share.tsx, js/packages/components/settings/MyBertyId.tsx
=> fix: copy to clipboard instead of share in web

js/packages/components/chat/MultiMemberSettings.tsx, js/packages/components/chat/OneToOneSettings.tsx, js/packages/components/chat/footer/ChatFooter.tsx, js/packages/components/chat/footer/record/RecordComponent.tsx, js/packages/components/onboarding/GetStarted.tsx, js/packages/components/settings/Accounts.tsx, js/packages/components/settings/Faq.tsx, js/packages/components/settings/Home.tsx, js/packages/components/settings/Network.tsx, js/packages/components/settings/PrivacyPolicy.tsx, js/packages/components/settings/Roadmap.tsx, js/packages/components/shared-components/WebViews.tsx
=> fix: hide useless buttons on web

js/packages/components/InfosChat.tsx, js/packages/components/NotificationBody.tsx, js/packages/components/chat/footer/ChatFooter.tsx, js/packages/components/chat/message/UserMessage.tsx, js/packages/components/chat/modals/EmojiKeyboard.modal.tsx, js/packages/components/main/CreateGroupFinalize.tsx, js/packages/components/main/home/Requests.tsx, js/packages/components/modals/ForwardToBertyContactModal.tsx, js/packages/components/settings/DevTools.tsx, js/packages/hooks/index.ts, js/packages/hooks/ui.hooks.ts, js/packages/store/context.ts, js/packages/store/provider.tsx, js/packages/store/types.ts
=> chore: move playSound out of react context

js/packages/components/main/Share.tsx
=> fix: scan qr with expo-camera

js/packages/components/chat/DeviceList.tsx, js/packages/components/chat/footer/ChatTextInput.tsx, js/packages/components/chat/message/UserMessage.tsx, js/packages/components/onboarding/GetStarted.tsx, js/packages/components/settings/AddDevConversations.tsx, js/packages/components/shared-components/SettingsButtons.tsx, js/packages/components/utils.ts, js/packages/i18n/index.ts, js/packages/i18n/locale/en-US/messages.json, js/packages/redux/reducers/theme.reducer.ts, js/packages/store/hooks.ts, js/tsconfig.json
=> feat: add i18n types for autocompletion

js/web/craco.config.js, js/web/src/polyfill/react-native-qrcode-svg/index.tsx
- not well sized on share screen
- doesn't display with circles
- doesn't display the Berty logo since it doesn't center
=> feat: add qr code on web

js/packages/native-modules/GoBridge/GoBridge.native.ts
=> fix: go bridge

js/android/app/build.gradle
=> fix: gradle version code and name generation

js/packages/screens/account/Opening/openClients.effect.ts
=> fix: await messenger events stream

go/cmd/berty/main.go, go/cmd/berty/p2p.go, go/cmd/berty/relay.go, go/cmd/berty/utils.go
=> feat: add relay and p2p cmd to berty main command

go/internal/messengerdb/db.go, go/pkg/bertyprotocol/api_app.go, go/pkg/bertyprotocol/api_contactrequest.go, go/pkg/bertyprotocol/store_message.go, go/pkg/bertyprotocol/store_metadata.go, tool/go.mod, tool/go.sum, tool/tyber/go/analyzer/analyzer.go, tool/tyber/go/analyzer/contactrequest.go, tool/tyber/go/analyzer/event.go, tool/tyber/go/analyzer/message.go, tool/tyber/go/analyzer/report.go, tool/tyber/go/cmd/manager.go, tool/tyber/go/go.mod, tool/tyber/go/go.sum, tool/tyber/go/main.go, tool/tyber/go/parser/parser.go
The analyzer module takes Tyber parser module logs to make statistics on contact requests and messages on Berty. Statistics are about the percentage of success and time to complete the task.
Here, an output of the analyzer module for 3 peers
``` json
{
"contactRequestReport": {
"contactRequests": [
{
"groupPK": "ZHRF8D3aKP2WEKY9XFnAq7EZFPascv5Sf95SgolhuSw",
"senderPK": "pH9lyBTMUqFzTTQRmLjjv50CcYHl0C4NXSQSbIHrWFE",
"senderDevicePK": "Hur1ROo3X8fu2zO_ByJ6N4x3dnsFdZmEFF9fBQCUp0g",
"receiverPK": "nBw81GhbYt4qT2oS-EFFYmg5licm_JgotiniKgqv5N8",
"receiverDevicePK": "8_-hQ9utc3u-ZZsjDvSpoo2NnCFAIlYhbI_GLmxVrl8",
"started": "2022-06-13T14:29:35.578904151+02:00",
"finished": "2022-06-13T14:29:35.786997079+02:00",
"succeeded": true
},
{
"groupPK": "mTv_abHY3SbSWxdHy9iDEVamuLRHjui0qF9VLYs2fz0", …
```
=> feat: add a tyber analyzer module

js/packages/components/chat/message/UserMessage.tsx, js/packages/components/inputs/large/LargeInput.tsx, js/packages/components/inputs/large/LargeInputWithIcon.tsx, js/packages/components/inputs/medium/MediumClearableInput.tsx, js/packages/components/inputs/medium/MediumInput.tsx, js/packages/components/inputs/small/SmallInput.tsx, js/packages/screens/settings/DeleteAccount/components/DeleteAccountContent.tsx
=> fix: blue background on pending message

go/internal/messengerpayloads/handlers.go, tool/tyber/go/analyzer/analyzer.go, tool/tyber/go/analyzer/contactrequest.go, tool/tyber/go/analyzer/group.go, tool/tyber/go/analyzer/message.go, tool/tyber/go/analyzer/report.go
Analyze sent messages to MultiMemberGroups to know how messages are successfully received.
Output:
``` json
{
"contactRequestReport": {
"contactRequests": null,
"sent": 0,
"received": 0,
"successPercent": 0,
"averageTime": 0,
"minTime": 0,
"maxTime": 0
},
"messageReport": {
"messages": [
{
"groupPK": "Q8DW6aKu5Eg_EuHFIZNFULCdyJnPHOKG53NopFv0sbQ",
"cid": "bafyreigfm5hvyapgcjb55txuw5kwnovnmp7isjbeqty3gn5ovr5yoxoywe",
"senderPK": "A6Z_fzXK6YrVl3pLUBK_X9Ac-uW_qDv-Uu1kQ4pwDjg",
"receiverPKs": [
"A6Z_fzXK6YrVl3pLUBK_X9Ac-uW_qDv-Uu1kQ4pwDjg",
"ZP0GP_mLY_8kMySehnoRZYJW77ky1W11Az6QtFXs4O4",
"ogg0TfXpzJN9g6w6wDNulT9zoqmrubpYRfHcSjgzoQ4"
],
"missinReceiverPKs": [],
"started": "2022-06-16T01:28:35.40294981+02:00",
"finished": "2022-06-16T01:28:35.696161985+02:00",
"succeeded": true
},
{
"groupPK": …
```
=> feat: analyze multimembergroups in Tyber

.github/dependabot.yml, .github/workflows/ssh-runner.yml
=> fix: dependabot labels and ssh workflow

js/packages/components/items/interfaces.ts, js/packages/components/items/section/MenuItemWithIcon.priv.tsx, js/packages/i18n/locale/en-US/messages.json, js/packages/redux/reducers/ui.reducer.ts, js/packages/screens/settings/SettingsHome/SettingsHome.tsx
=> feat: add version + devmode buttons in settings

js/packages/components/shared-components/SettingsButtons.tsx
=> fix: quick fix for StringOptionInput component

.github/ISSUE_TEMPLATE/bug_template.yml
=> docs: update label name for bug template

js/packages/components/InfosChat.tsx
=> fix: retry button contact request behavior

.github/workflows/ios.yml, js/e2e-tests/README.md, js/e2e-tests/lib.js
=> feat: run e2e basic test on CI

js/packages/mock-services/fakeGeneration.ts, js/packages/mock-services/static/messengerServiceMock.ts, js/packages/redux/reducers/messenger.reducer.ts, js/packages/utils/testing/mockServices.test.ts
=> feat: implem peer network status redux models

js/packages/i18n/locale/en-US/messages.json, js/packages/redux/reducers/persistentOptions.reducer.ts, js/packages/screens/account/Opening/OpeningAccount.tsx, js/packages/screens/settings/DevTools/DevTools.tsx
=> feat: add forceMock value in redux store

.github/ISSUE_TEMPLATE/bug_template.yml
Remove bug icon from bug template title
=> docs: remove icon from bug template title

.github/workflows/ios.yml, .github/workflows/mac.yml
=> ci: try to fix setup asdf actions error

.github/workflows/ios.yml, .github/workflows/mac.yml
=> chore: rename folder to ci-self-hosted

.github/workflows/ios.yml
=> ci: fix cocoapods encoding

.github/workflows/ios.yml, js/Makefile
=> ci: disable yolo build on ios workflow

.github/workflows/ios.yml, .github/workflows/monitor-runners.yml
=> ci: fix finding most recent e2e build

.github/workflows/ios.yml
=> ci: fix find latest e2e build

go/pkg/bertyprotocol/service.go
=> fix: reduce noisy logs

js/ios/Podfile.lock, js/packages/components/chat/message/user-message/user-message-box/FileMessage.tsx, js/packages/hooks/react.hooks.ts, js/packages/screens/chat/Home/components/Search.tsx, js/packages/screens/chat/Home/components/conversation/ConversationButton.tsx, js/packages/screens/chat/Share/Share.tsx, js/packages/screens/settings/SettingsHome/components/EditMyProfile.tsx
=> fix: UI front fixes

go/pkg/bertyaccount/service_account.go
fixes https://github.com/berty/zenhub/issues/19
=> fix: account create then import flow

go/pkg/banner/quote.go
Add additional quotes related to Berty.
=> Add additional quote

.github/workflows/ios.yml, .github/workflows/mac.yml, .github/workflows/monitor-runners.yml, .github/workflows/utils/get-self-hosted-runner-status.js, .github/workflows/utils/mac-runner-matrix-builder.js, tool/ci-self-hosted/Makefile
=> ci: fix url path (orgs vs repo)

go/cmd/berty/main.go, go/internal/cryptoutil/keystore_message_utils_test.go, go/internal/initutil/manager.go, go/internal/initutil/manager_test.go, go/internal/initutil/node.go, go/internal/omnisearch/manager.go, go/pkg/bertyaccount/service_account.go, go/pkg/bertymessenger/service_non_mocked_test.go, go/pkg/bertyprotocol/api_multimember.go, go/pkg/bertyprotocol/blackbox_test.go, go/pkg/bertyprotocol/deactivate_test.go, go/pkg/bertyprotocol/group_context.go, go/pkg/bertyprotocol/orbitdb.go, go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go, go/pkg/bertyprotocol/orbitdb_test.go, go/pkg/bertyprotocol/scenario_test.go, go/pkg/bertyprotocol/service.go, go/pkg/bertyprotocol/service_group.go, go/pkg/bertyprotocol/store_metadata_test.go, go/pkg/bertyprotocol/testing.go, go/pkg/bertyprotocol/testing_test.go, go/pkg/bertyreplication/services_replication_test.go
fixes https://github.com/berty/zenhub/issues/18
cherry-picked from: #4251
=> fix: deactivate group

go.mod, go.sum
=> chore: moved gomobile from aeddi's fork to berty's one

.github/workflows/ios.yml, .github/workflows/mac.yml
=> ci: add post/pre checkout cleanup on macos build job

js/android/app/build.gradle, js/android/app/src/main/java/tech/berty/gobridge/GoBridgeModule.java, js/ios/Berty/Sources/Bridge/GoBridge.swift, js/ios/Podfile.lock, js/ios/berty.yaml, js/packages/utils/global-persistent-options/defaults.ts
=> fix: Activate logs by default in Debug, Staff and Yolo build variants

go.mod, go.sum
=> chore: bump gomobile version

js/Makefile, js/ios/berty.yaml
=> ci: add the PR number to the product name

.github/workflows/ssh-runner.yml
=> ci: fix ssh workflow for windows

.github/workflows/go.yml, .github/workflows/release.yml, .github/workflows/ssh-runner.yml
=> ci: fix go install (asdf) on windows

.github/workflows/ios.yml, js/Makefile, js/e2e-tests/basic.js, js/e2e-tests/lib.js, js/e2e-tests/package-lock.json, js/e2e-tests/package.json, js/ios/Podfile.lock, js/package.json, js/yarn.lock
=> chore: upgrade appium

config/config.gen.json, config/config.yml, go/internal/config/config.gen.go, js/packages/config/global.gen.js
=> feat: update relay config

go/README.md
=> chore: update go readme

.github/workflows/benchmark.yml
=> fix: benchmark on master

config/config.gen.json, config/config.yml, go/internal/config/config.gen.go, go/internal/initutil/ipfs.go, go/internal/initutil/manager_test.go, go/internal/ipfsutil/repo.go, go/pkg/bertyprotocol/deactivate_test.go, js/packages/config/global.gen.js, js/packages/utils/accounts/defaultCLIArgs.ts, tool/berty-mini-local-helper/Makefile
enable quic tpt (with disable reuseport opt)
=> feat: enable quic transport

.github/workflows/release.yml
=> ci: fix testflight release

js/ios/Podfile.lock, js/package.json, js/packages/components/chat/MessageList.tsx, js/yarn.lock
=> fix: implem FlashList instead of FlatList

js/packages/hooks/accounts.hooks.ts, js/packages/screens/account/SelectNode/SelectNode.tsx, js/packages/utils/accounts/closeAccount.ts, js/packages/utils/accounts/deleteAccount.ts, js/packages/utils/bridge/bridge.ts
=> fix: close bridge before any account functions

js/Makefile, js/packages/components/chat/MessageList.tsx, js/packages/components/chat/footer/ChatFooter.tsx, js/packages/screens/chat/MultiMember/components/HeaderTitle.tsx
- Disable member bar in MultiMember conversations (until we found a better behavior/UI/UX)
- Disable simple `onPress` on MultiMember title in MultiMember conversations
- Keyboard is no longer hidden after sending a message
=> fix: UI fixes from testing session

.github/workflows/ios.yml
=> fix: disable e2e tests ci jobs

.tool-versions, js/README.md
- some improvements on the readme file, adding more info to facilitate the installation process.
- bump ruby to fix an issue on mac m1
=> chore(js): Update Readme

js/android/app/src/main/res/values/styles.xml, tool/game-utils/game-dev-app/android/app/src/main/res/values/styles.xml
- App was using the Android dark theme as default.
Reference: https://developer.android.com/develop/ui/views/theming/darktheme
Fix https://github.com/berty/berty/issues/4626
=> fix: remove Android dark theme

go.mod, go/framework/bertybridge/bridge.go, go/internal/initutil/ipfs.go, go/internal/initutil/manager.go, go/internal/mdns/mdns.go, go/internal/mdns/mdns_test.go, go/pkg/bertyaccount/service.go, go/pkg/bertyaccount/service_account.go
=> feat: mdns restart on network change

.github/workflows/valist.yml
Signed-off-by: Alec M. Wantoch <alec@wantoch.com>
This updates the Valist GitHub Action to support new IPFS infra & meta-transactions powered by OpenZeppelin Defender, and an upgraded platform metadata spec :)
=> Update valist.yml to support better IPFS & meta-tx infra

go/cmd/berty/mini.go, go/cmd/berty/mini/main.go, go/cmd/berty/mini/view_group_outgoing.go, go/cmd/berty/mini/view_tabbed_groups.go, go/internal/initutil/ipfs.go, go/internal/initutil/manager.go, go/pkg/bertyaccount/service.go, go/pkg/bertyaccount/service_account.go
=> feat: new command in mini to get and set the state of the netmanager

js/README.md, js/ios/Podfile, js/ios/Podfile.lock, js/package.json, js/yarn.lock
=> chore: support react-devtools on flipper

go/README.md
Added a little explenation on how to use berty mini to the CLI readme, so people understand how the basics work to play around.
=> Mini readme

js/ios/Podfile.lock, js/packages/screens/settings/DevTools/DevTools.tsx, js/packages/utils/global-persistent-options/defaults.ts
=> fix: change devtools default log filter

go/cmd/berty/mini/view_group_outgoing.go, go/pkg/bertybot/bot.go, go/pkg/bertybot/handlers.go, go/pkg/bertybot/recipes.go
Here is a PR to:
- improve bertybot package (handle auto-accept invite)
- make it easy to interact with bot in berty mini (handle "//" to write a single "/")
=> feat: improve bot experience

js/packages/components/create-group/CreateGroupFooter.priv.tsx, js/packages/components/create-group/CreateGroupHeader.tsx, js/packages/components/inputs/medium/MediumInput.tsx, js/packages/components/shared-components/ContactPicker.tsx, js/packages/screens/account/SelectNode/__snapshots__/SelectNode.test.tsx.snap, js/packages/screens/chat/CreateGroupAddMembers/CreateGroupAddMembers.tsx, js/packages/screens/chat/CreateGroupAddMembers/__snapshots__/CreateGroupAddMembers.test.tsx.snap, js/packages/screens/chat/CreateGroupFinalize/CreateGroupFinalize.tsx, js/packages/screens/chat/CreateGroupFinalize/__snapshots__/CreateGroupFinalize.test.tsx.snap, js/packages/screens/chat/MultiMemberSettingsAddMembers/MultiMemberSettingsAddMembers.tsx, js/packages/screens/chat/MultiMemberSettingsAddMembers/__snapshots__/MultiMemberSettingsAddMembers.test.tsx.snap
fix for issue #4390
Signed-off-by: LFGaming (Luke) <github@luke.irtl.nl>
=> Remove yellow-ish background from group chats

go/cmd/berty/scenario_test.go, go/framework/bertybridge/blackbox_test.go, go/pkg/bertyaccount/blackbox_test.go, go/pkg/bertymessenger/service_test.go, go/pkg/bertyreplication/services_replication_test.go
=> chore: remove refs to deprecated io/ioutil

js/packages/screens/settings/ThemeEditor/ThemeEditor.tsx
This PR fix the CI issue on https://github.com/berty/berty/pull/4809
Signed-off-by: Iuri Pereira <iuricmp@gmail.com>
=> fix: null check

go/internal/initutil/ipfs.go, tool/infra-testing-tool/go/cmd/test_start.go
=> chore: remove repetitive words

tool/github-actions/scw-funcs/benchs-hook/README.md, tool/infra-testing-tool/go/server/testclient/main.go
=> tool: fix some typos

.github/workflows/integration.yml, tool/berty-mini/cluster/commander, tool/deployments/rdvp-dev/Makefile, tool/deployments/testbot/Makefile, tool/deployments/watchtower/Makefile, tool/deployments/welcomebot/Makefile, tool/integration-compose/Makefile
Fixes issue https://github.com/berty/berty/issues/4829
=> fix: Change docker-compose to docker compose to fix CI

go/internal/messengerdb/db.go, go/pkg/bertybridge/service_grpc.go, tool/infra-testing-tool/go/config/node.go
=> chore: fix function name in comment

config/config.gen.json, config/config.yml, go/pkg/config/config.gen.go, js/packages/config/global.gen.js
Tested with Android phone on cell network and iOS simulator on house network.
=> fix: In config.yml, update addresses for rdvp and static-relays

go/README.md
=> chore: update go/README.md

js/packages/screens/settings/DeleteAccount/DeleteAccount.tsx, js/packages/screens/settings/DeleteAccount/__snapshots__/DeleteAccount.test.tsx.snap
Enhance the clarity of the account deletion instructions in the settings screen.
fix #4300
=> Clarify account deletion process
