berty/berty

core/cmd/berty/main.go

Fixes #1754.5 :
```
$ go build .
./warning.go:3:3: warning: #warning This version is outdated please use github.com/berty/berty/v2 instead. [-Wcpp]
3 | // #warning This version is outdated please use github.com/berty/berty/v2 instead.
|   ^~~~~~~
```
It may be placed elsewhere in the repo (I would suggest to move it in the entry point of the lib) so user using `go mod` would also get the warn but I'm not sure of where it is.

Warn user for using the v1 version.

---

deprecated.go

fix: add top-level go package with deprecation warning

---

core/cmd/berty/main.go
core/node/node.go

This place is better because we are sure everyone is gonna be warned, someone using it as a lib (which for the first version its very improbable) is still gonna see the error message.

fix: Moving depreacation in node for go mod user.

---

client/ios/Berty/Info.plist

When launching the app, an error occurred at startup:
```
This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSBluetoothAlwaysUsageDescription key with a string value explaining to the user how the app uses this data.
```
According to this error message, I add that key to Info.plist.

fix: launch error because of bluetooth privilege required

---

go/cmd/berty/mini/main.go
tool/berty-mini-cluster/commander
tool/berty-mini-cluster/docker-compose.yml

This PR bootstraps the mini tool `./tool/berty-mini-cluster` which allows starting `berty mini` under various contexts (with/without docker, with/without network bridge, etc)
The current state is relatively poor in term of use cases, but can easily be updated as soon as we find new testing ideas
Replaces #1748

feat(tool): berty mini cluster with tmux

---

go/cmd/berty/main.go
go/cmd/rdvp/main.go
go/internal/banner/quote.go
go/internal/cryptoutil/cryptoutil.go
go/internal/ipfsutil/api_inmemory.go
go/internal/ipfsutil/cfg.go
go/internal/ipfsutil/testing.go
go/internal/tinder/driver_rdv.go
go/pkg/bertydemo/client.go
go/pkg/bertyprotocol/events.go
go/pkg/bertyprotocol/group.go
go/pkg/bertyprotocol/group_test.go
go/pkg/bertyprotocol/keystore_message.go
go/pkg/bertyprotocol/keystore_message_utils.go
go/pkg/bertyprotocol/orbitdb_many_adds_test.go
go/pkg/bertyprotocol/store_metadata.go
go/pkg/bertyprotocol/store_metadata_test.go

This PR:
- Moves all common crypto utils in cryptoutil internal package
- Refactores methods that were using these utils
- Aliases `math/rand` -> `mrand` and `crypto/rand` -> `crand` to disambiguate the random source when reading the code

refactor: disambiguate rand packages and reorganize cryptoutil

---

deployments/rdvp-dev/Makefile
deployments/rdvp-dev/docker-compose.yml

First deployment here: `/ip4/167.99.223.55/tcp/4040/p2p/QmTo3RS6Uc8aCS5Cxx8EBHkNCe4C7vKRanbMEboxkA92Cn`
[DNSADDR](https://github.com/multiformats/multiaddr/blob/master/protocols/DNSADDR.md) configured: `/dnsaddr/rdvp.berty.io`

chore: add rdvp deployment helpers + configure docker to use host network

---

go/.golangci.yml
go/cmd/berty/main.go
go/cmd/berty/mini/main.go
go/cmd/berty/mini/view_group.go
go/cmd/berty/mini/view_group_incoming.go
go/cmd/berty/mini/view_group_outgoing.go
go/cmd/berty/mini/view_tabbed_groups.go
go/internal/testutil/logging.go
go/pkg/bertydemo/client.go
go/pkg/bertyprotocol/api_event.go
go/pkg/bertyprotocol/api_group.go
go/pkg/bertyprotocol/api_multimember.go
go/pkg/bertyprotocol/client.go
go/pkg/bertyprotocol/group.go
go/pkg/bertyprotocol/group_context.go
go/pkg/bertyprotocol/keystore_message_utils_test.go
go/pkg/bertyprotocol/orbitdb.go
go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
go/pkg/bertyprotocol/orbitdb_utils_test.go
go/pkg/bertyprotocol/scenario_test.go
go/pkg/bertyprotocol/service.go
go/pkg/bertyprotocol/service_group.go
go/pkg/bertyprotocol/service_test.go
go/pkg/bertyprotocol/store_message.go
go/pkg/bertyprotocol/store_metadata.go
go/pkg/bertyprotocol/store_metadata_index.go
go/pkg/bertyprotocol/testing.go
go/pkg/bertyprotocol/testing_test.go
go/pkg/bertytypes/contact.go

- Use real grpc client in berty mini instead of using service directly
- Add scenario test to protocol
- Fixup wrong context passed to `ActivateGroup` method

feat(protocol): replace service with grpc client

---

.buildkite/pipeline.yml

there is a plan to fix those issues at the root, but for now, we regularly have
annoying failures, mainly on CI which is probably just already allocating too
much CPU on other things
this PR should avoid getting to the admin to manually retry go-build

chore: reduce CI failures on go build

---

go/Makefile
go/gen.sum

Some makefile rules that depends on bazel doesn't works anymore
fix #1804

Some Makefile rules doesn't works inside the go folder

---

js/packages/hooks/Chat.tsx
js/packages/store/chat/conversation.ts

Fixes #1854 
This also always show the sample conversations as requested by the ux team

Don't create conversation until contact has accepted request

---

js/packages/berty-app/App.tsx
js/packages/berty-app/custom-icons-svgs/id.svg
js/packages/berty-storybook/Onboarding.tsx
js/packages/berty-storybook/chat/Chat.tsx
js/packages/berty-storybook/chat/ChatGroup.tsx
js/packages/berty-storybook/chat/shared-components/Chat.tsx
js/packages/berty-storybook/main/CreateGroup.tsx
js/packages/berty-storybook/main/List.tsx
js/packages/berty-storybook/main/ListModal.tsx
js/packages/berty-storybook/main/Scan.tsx
js/packages/berty-storybook/main/ScanRequest.tsx
js/packages/berty-storybook/main/Search.tsx
js/packages/berty-storybook/modals/SendContactRequest.tsx
js/packages/berty-storybook/settings/Home.tsx
js/packages/berty-storybook/settings/MyBertyId.tsx
js/packages/berty-storybook/shared-components/Footer.tsx
js/packages/berty-storybook/shared-components/Header.tsx
js/packages/berty-storybook/shared-components/Modal.tsx
js/packages/berty-storybook/shared-components/SettingsButtons.tsx

Fixes #1916 
This replaces all uses of SafeAreaView from react-native to the one from react-native-safe-area-context which is more stable and has a better api
This also restores the touch feedback on various buttons
This also fixes the "id" svg which circle was skewed

Fix footer shaking

---

js/gen.sum
js/package.json
js/packages/components/settings/MyBertyId.tsx
js/packages/components/shared-components/Request.tsx
js/yarn.lock

Makes the MyBertyId modal responsive (in this case, scrollable on landscape view, otherwise there should never be any overflow).
TODO:
Relates to #1984
Closes #1998

fix(chat): responsive BertyId modal

---

.buildkite/pipeline.yml
go/Makefile
go/gen.sum

the `bigcores` queue can be run multiple times per host
this queue can only be deployed once per host

chore: run go-build on a dedicated queue so it can only be run once per host in parallel

---

js/packages/components/Onboarding.tsx
js/packages/components/modals/DeleteAccount.tsx

Name input was already fixed; this adds 'Delete' confirmation field + port number input in dev onboarding
Closes #1928

fix: text input text is black in dark iOS mode

---

go/cmd/berty/main.go
go/cmd/berty/mini/view_group_outgoing.go

chore: generate halfblock qrcodes on terminal to support smaller screens or splitted layouts

---

js/packages/hooks/message.ts
js/packages/store/messenger/message.ts
js/packages/web-dev-app/src/App.tsx

- Create hook and selector for searching body text of messages sent by humans
- Add a Search tab to web-dev-app to demo contact and message searching
nb
- Not tested for edge cases or very heavy data search volume
Closes #2043

feat(front): add basic message body search to store

---

.github/workflows/go.yml

report.ci should allow us to have annotations directly in the "Files changed" tab as soon as a unit test or a go build issue is introduced

feat: set up report.ci

---

js/packages/styles/constant.ts

Very small change, just updates current initial scaleSize calculation based on device orientation (previously it assumed portrait, so loading the app in landscape would cause scaling issues).
Closes https://github.com/berty/berty/issues/2136

fix: get initial scale size based on device orientation

---

.github/workflows/go.yml

This reverts commit d71e0ee5a71e7bd080ccd41bffd2eeabe55535e2.
It does not work as expected, and makes logs very hard to read (JSON output)

chore: Revert "feat: set up report.ci"

---

js/Makefile
js/gen.sum

- Adds env variable options with defaults to some commands (not exhaustive)
- Adds `.quick` targets for `lint` and `test` (`deps` verification is currently too slow to use repeatedly)

chore: JS makefile: add env args and no-dep make targets

---

.github/workflows/pr.yml

set up this: https://github.com/marketplace/actions/release-notes-preview

chore: set up release not preview on PR

---

js/Makefile
js/gen.sum

* add a new `make bridge.start.docker` rule in `js/`
* tested with latest Docker for Mac
* cc @alexarsh
* `cd js; make bridge.start.docker` in a terminal
* `cd js; make metro.start` in another one
* `cd js; make ios.run` from a last one
* in the iOS simulator, let the default `External` toggle + `1337` port

chore(js): add 'make bridge.start.docker' rule

---

js/packages/components/main/Search.tsx
js/packages/styles/map-declaration.ts
js/packages/styles/types.ts

Adds non-abstract flex utils, so we can now use:
`flex.direction` (flexDirection), `flex.align` (alignItems), `flex.justify` (justifyContent)
The old flex abstractions are still possible to use (`row.left` for example)
Closes #2141

feat(js): add flex utils to style API

---

.github/workflows/go.yml

Last update on golangci-lint-action (https://github.com/golangci/golangci-lint-action/pull/34) requires having golangci-lint v1.28.3

fix: broken golangci github action

---

js/packages/components/main/HomeModal.tsx
js/packages/components/main/Scan.tsx
js/packages/components/settings/MyBertyId.tsx
js/packages/styles/constant.ts

Just quick fixes to remove blocking responsiveness issues (i.e. can't access some interactive UI element).
- QR scanner now always fits on screen
- Main modal is dismissable and interactive on short or landscape screen
- QR scan page is scrollable for access to manual deeplink add form
Related to #1852

fix(messenger): fix main modal and QR scanner sizing

---

js/packages/components/chat/ChatGroup.tsx
js/packages/components/chat/shared-components/Message.tsx

Credit for this goes to 
- Adds avatar and username (already done by @clegirar or @n0izn0iz, I've just added it back)
- Puts username inside message body container
- Hides username, timestamp and avatar on follow-up messages (messages where previous message is from same non-self user and is more than 10 minutes time difference)
Closes #2187

feat(messenger): add avatar and name to multimember conversation

---

js/packages/components/Onboarding.tsx
js/packages/components/chat/MultiMemberQR.tsx
js/packages/components/main/CreateGroupAddMembers.tsx
js/packages/components/main/CreateGroupFinalize.tsx
js/packages/components/main/HomeModal.tsx
js/packages/components/main/Scan.tsx
js/packages/components/main/Search.tsx
js/packages/components/settings/EditProfile.tsx
js/packages/components/settings/Home.tsx
js/packages/components/settings/MyBertyId.tsx
js/packages/components/shared-components/CircleAvatar.tsx
js/packages/components/shared-components/ProceduralCircleAvatar.tsx
js/packages/eslint-config/index.js
js/packages/styles/constant.ts
js/packages/styles/hook.tsx

- Provide windowHeight, windowWidth, isLandscape, isGteIpadSize in styles API (useage in components: `const ({...styles},{ isLandscape, windowWidth, windowHeight, isGteIpadSize }) = useStyles()`
- Remove all use of useDimensions hook in components package (meaning that current windowHeight and windowWidth can be accessed as above)
- Add `scaleSize` to many absolute sizes (not exhaustive, but should be consistent within files) explicity (~_someSize: 12~ -> `_someSize: 12 * scaleSize`), or implicitly with API (e.g. ~style={{height: 30}}~ -> `style={height(30)}`). _For now the only visible change to UI will be in screens narrower than iPhone 11_
- Fixes some small layout-related UI bugs I came across while doing this
Also:
- fix: animation lag in Privacy onboarding component (forgot to add …

chore(front): Use dynamic UI scale values from styles API

---

go/internal/testutil/logging.go

Specific to go tests
Currently, when running `go test -v`, you don't have any berty logging (nop logger), you need to call `go test -v --debug`
This PR changes this behavior by returning a zap logger with min level==error
Note that if you rn `go test` without `-v` you won't have any logging
Warning, this PR makes tests a lot more verbose, but I think it's a good thing to motivate us cleaning up some logs, especially orbit-db ones

chore: display errors and above on unit tests by default

---

.github/workflows/go.yml
go/Makefile
go/framework/bertybridge/bridge_test.go
go/gen.sum
go/internal/handshake/handshake_test.go
go/internal/testutil/skip.go
go/pkg/bertymessenger/service_test.go
go/pkg/bertyprotocol/contact_request_manager_test.go
go/pkg/bertyprotocol/keystore_message_utils_test.go
go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
go/pkg/bertyprotocol/orbitdb_test.go
go/pkg/bertyprotocol/scenario_test.go
go/pkg/bertyprotocol/store_message_test.go
go/pkg/bertyprotocol/store_metadata_test.go
go/pkg/bertyprotocol/tinder_swiper_test.go

feat: improve scenario test

---

go/cmd/berty/mini/main.go
go/framework/bertybridge/bridge_protocol.go
go/internal/config/berty.go
go/internal/ipfsutil/repo.go
go/internal/multipeer-connectivity-transport/transport.go

bug: negative counter in the **WaitGroup** field of the `Listener` struct.
In outgoing connections (`Dial()` method), no **Add** method of WaitGroup is called. So when `newConn` calls **Done** of WaitGroup, the counter becomes negative.
Signed-off-by: d4ryl00 <d4ryl00@gmail.com>

fix: Panic in WaitGroup in the Multipeer Connectivity transport

---

go/pkg/bertymessenger/testing.go
go/pkg/bertyprotocol/contact_request_manager.go
go/pkg/bertyprotocol/service_group.go
go/pkg/bertyprotocol/store_message.go
go/pkg/bertyprotocol/store_message_test.go
go/pkg/bertyprotocol/store_metadata.go

- Should Subscribe() before do listen subscribed events in go routine to prevent later schedule go routine - lost events
- inherit orbitdb's logger in metadata_store
- Fix missing mutex unlock in test
Run current tests

fix: improve subscribe + some small improvement for logging/testing

---

go/internal/multipeer-connectivity-transport/connmgr.go
go/internal/multipeer-connectivity-transport/discovery.go
go/internal/multipeer-connectivity-transport/listener.go
go/internal/multipeer-connectivity-transport/transport.go

The global variable `gListener` is not protected by concurrent execution.
For now, this transporter supports only once instance.
Signed-off-by: d4ryl00 <d4ryl00@gmail.com>

fix: race condition in the MultipeerConnectivity transporter

---

js/packages/berty-app/android/app/src/main/AndroidManifest.xml
js/packages/berty-app/ios/Berty/Info.plist

As it says on the tin. I'm not removing orientation conditions/listeners from UI for the moment; this is to unblock the issue of broken landscape views that are too time-consuming to maintain.

feat(messenger): lock portrait mode on mobile

---

go/framework/bertybridge/bridge_test.go
go/internal/multipeer-connectivity-transport/discovery.go

Signed-off-by: phanquy <phanhuynhquy@gmail.com>
Some improve in HandleFoundPeer()
- Missing mutex and checking valid of gListener in go routine forked in HandleFoundPeer() - so if Listener.Close() is called, potentially gListener is set is nill before go routine is executed
- mutex cover also  the case `case listener.inboundConnReq <- connReq{` - this can be blocked in case missing call to Accept(), and will block Close(), Dial()...
None

fix: multipeer transport race condition

---

js/packages/components/chat/MultiMember.tsx
js/packages/components/chat/OneToOne.tsx
js/packages/components/main/Home.tsx
js/packages/components/main/Search.tsx
js/packages/components/package.json
js/packages/components/settings/Home.tsx
js/packages/components/shared-components/SwipeNavRecognizer.tsx
js/yarn.lock

- Adds a component that triggers a back navigation on swiped-right child (uses simple external module https://github.com/glepur/react-native-swipe-gestures based on RN's PanResponder)
- Component takes arbitrary callbacks for horizontal swipes that can override goBack()
- Implemented in main bottom tab views, Search/Settings/Home
- Implemented in OneToOne chat
I didn't put this everywhere as I'm not sure I'm happy with it.

feat(messenger): improve swipe screen navigation

---

go/internal/testutil/logging.go

Usage: `BERTY_LOGFILTERS=":default: debug+:*.odb" go test ......`

chore: configure :default: pattern replacement for testutil.Logger

---

Dockerfile
go/Makefile
go/cmd/berty/version.go
go/gen.sum
js/Makefile
js/gen.sum

* avoid polluting user's PATH fs
* avoid managing support for people using a misconfigured PATH env var
* Makefile styling: move .PHONY lines below their rule definitions and separate rules by two newlines
* remove BuildTime from LDFLAGS to maximize go's binary caching system
* make `berty version` dynamic
* check for support go version in the Makefile

chore: various Makefile improvements

---

go/internal/multipeer-connectivity-transport/driver/bridge_darwin.go
go/internal/multipeer-connectivity-transport/driver/bridge_unsupported.go
go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge_darwin.go
go/internal/multipeer-connectivity-transport/driver/mc-driver/cgo_bridge_unsupported.go

an even better version could be:
* 3 files:
* `darwin,cgo`   -> real driver
* `darwin,!cgo`  -> noop driver that returns an init error "requires building with CGO"
* `!darwin` -> noop driver that returns an init error "only available on darwin platforms" 
btw @D4ryl00, can you note somewhere that this package should be flatten into a unique package without sub-package

chore: update mpconnectivity build constraints

---

go/internal/tinder/driver_localdiscovery.go

Signed-off-by: phanquy <phanhuynhquy@gmail.com>
Missing close channel peer can results into blocking finding peers
NA

fix: missing close empty channel

---

go/internal/packingutil/packing.go

Signed-off-by: Jorropo <jorropo.pgm@gmail.com>

chore: Fixing typo in go/internal/packingutil/packing.go.

---

js/packages/components/main/Home.tsx
js/packages/components/main/Scan.tsx
js/packages/components/settings/MyBertyId.tsx

- enable vertical swipe on Scan and MyBertyId QR screens
- organize imports
- fix: checking keys on empty persistentOpts crashes Home

feat(messenger): Allow swiping back on the MyBertyId and Scan QR views

---

.github/workflows/ios.yml

This PR:
* mimics the structure of a .ipa file without the signature stuff
* use a specific artifact name suffix to help yolo detect the artifact as an unsigned .ipa
Basically, this ipa is not installable (lack of signature), but is correct for most tools parsing .ipa archives

chore: update yolo-friendly artifact suffix

---

go/framework/bertybridge/bridge_protocol.go
go/internal/initutil/node.go

Ignore API Ipfs errors to allow two Berty instances in the same place

fix: ignore ipfs api errors

---

go.mod
go.sum
go/framework/bertybridge/bridge_protocol.go
go/internal/initutil/node.go
go/pkg/bertymessenger/db.go
go/pkg/bertymessenger/db_test.go
go/pkg/bertymessenger/service.go
go/pkg/bertymessenger/testing.go

fix: bump gorm and avoid syntax error

---

js/Makefile
js/gen.sum

This PR repairs the versioning in the system info view
However, it has a strange bug showing a commit sha that I never committed myself, I will investigate in a further PR why it happens and I will maybe update the Makefile to compute the "last known" sha if it's specific to github actions

fix: restore git version in system info on mobile

---

.github/workflows/android.yml
.github/workflows/go.yml
.github/workflows/ios.yml
.github/workflows/release.yml

* `fetch-depth: 42` on `iOS` and `Android`, to increase chances of determining "pretty" version based on previous known tag
* `persist-credentials: false`, small security improvement
* `ref: ${{ github.event.pull_request.head.sha }}`, see https://github.com/actions/checkout/issues/299
* switch go versions to `1.15.x` instead of fixed patch version

chore(ci): use expected commit at checkout for versionning

---

go/cmd/betabot/main.go
go/cmd/testbot/main.go
go/pkg/bertybot/bot.go
go/pkg/bertybot/bot_test.go
go/pkg/bertybot/commands.go
go/pkg/bertybot/context.go
go/pkg/bertybot/example_test.go
go/pkg/bertybot/handlers.go
go/pkg/bertybot/opts.go
go/pkg/bertybot/recipes.go
go/pkg/bertymessenger/service_test.go
go/pkg/bertymessenger/testing.go
go/pkg/bertymessenger/testing_test.go
go/pkg/bertymessenger/types.go

* add a new `cmd/testbot` binary with a target of being used in unit tests, and maybe by developers (humans)
* add a new `pkg/bertybot` helper package
* only used by `cmd/testbot` for now, but there is plan to migrate `cmd/betabot` on it
* export some bertymessenger's testing helper to allow easier bertymessenger testing in other packages

feat: pkg/bertybot + cmd/testbot

---

js/packages/components/chat/OneToOne.tsx
js/packages/components/chat/shared-components/Chat.tsx
js/packages/components/helpers.ts
js/packages/components/main/Home.tsx

In 1-1 chatrooms:
- re-add chat header date format
- add sticky date header on scroll (Today, Yesterday, DD/MM/YYYY)
- add date dividers between messages on different days (same format as above)
- **does not** add date headers/dividers to multimember chatrooms yet; it will be the same implementation so I'm making sure it's smooth in 1-1 first

feat(messenger): sticky date dividers in 1-1 chatrooms

---

js/packages/components/chat/MultiMember.tsx
js/packages/components/chat/OneToOne.tsx

Related to #2463 and #2465 – since I won't have time to test the fix to remove sticky headers when conversation start is visible, this removes the headers (but keeps dividers in 1-1 and adds them to multimember.)

fix(messenger): hotfix remove stickydate + add multimember date dividers

---

js/packages/components/chat/shared-components/Message.tsx

Even if we solve the current issue, it makes sense to have a user-friendly error message in place somewhere.

fix: add user friendly error message on invitation error

---

go/internal/initutil/manager_test.go

Recently the CI started to somtimes fail with these new detected leaks
```
2020-10-13T09:18:55.3352905Z === RUN   TestCloseByContext
2020-10-13T09:18:55.3353356Z     leaks.go:78: found unexpected goroutines:
2020-10-13T09:18:55.3354194Z         [Goroutine 10467 in state select, with github.com/libp2p/go-mplex.(*Multiplex).Accept on top of the stack:
2020-10-13T09:18:55.3354774Z         goroutine 10467 [select]:
2020-10-13T09:18:55.3355481Z         github.com/libp2p/go-mplex.(*Multiplex).Accept(0xc002798680, 0xc001722600, 0x100000000, 0x2700000000)
2020-10-13T09:18:55.3356471Z         	/home/runner/go/pkg/mod/github.com/libp2p/go-mplex@v0.1.3/multiplex.go:129 +0x129
2020-10-13T09:18:55.3358095Z         github.com/libp2p/go-libp2p-mplex.(*conn).AcceptStream(0xc002798680, 0x0, 0xdb7e6e, …
```

chore: add new functions to ignore list of goleak

---

go/pkg/bertyprotocol/group.go
go/pkg/bertyprotocol/orbitdb.go
go/pkg/bertyprotocol/orbitdb_many_adds_berty_test.go
go/pkg/bertyprotocol/orbitdb_test.go
go/pkg/bertyprotocol/service.go
go/pkg/bertyprotocol/service_group.go
go/pkg/bertyprotocol/services_replication_test.go
go/pkg/bertyprotocol/store_metadata.go
go/pkg/bertyprotocol/store_metadata_index.go
go/pkg/bertyprotocol/store_metadata_test.go

- allow the account group to be launched in local only mode (orbit-db will not sync store with other peers)
- send secrets and tag peers on account group
- force sending memberDevice and secrets during contact group init

feat: refactor account and contact group init

---

.github/workflows/go.yml
go/assets/example_test.go
go/cmd/berty/mini/example_test.go
go/cmd/betabot/example_test.go
go/cmd/rdvp/example_test.go
go/cmd/testbot/example_test.go
go/framework/bertybridge/internal/bridgepb/example_test.go
go/internal/lifecycle/example_test.go
go/internal/multipeer-connectivity-transport/driver/example_test.go
go/internal/multipeer-connectivity-transport/example_test.go
go/internal/multipeer-connectivity-transport/multiaddr/example_test.go
go/internal/notification/example_test.go
go/internal/packingutil/example_test.go
go/internal/sysutil/sysutil.go
go/internal/sysutil/sysutil_unix.go
go/internal/sysutil/sysutil_unsupported.go
go/internal/testutil/example_test.go
go/internal/tools/example_test.go
go/pkg/bertymessenger/api.go
go/pkg/bertyprotocol/api_debug.go
go/pkg/bertytypes/example_test.go
go/pkg/bertyversion/example_test.go
go/pkg/username/example_test.go

* create empty test files in packages without ones to force `go test` trying to build them
* add a windows job on the CI that checks if the project compiles
* make the project installable/testable on windows

fix: test windows on CI

---

go/pkg/tempdir/tempdir.go
go/pkg/tempdir/tempdir_android.go
go/pkg/tempdir/tempdir_darwin.go
go/pkg/tempdir/tempdir_others.go

We should pass the result of the `getCacheDir().getAbsolutePath()` Java method to `SetAndroidCacheDir(path)`.
Could be done in #2499 :) (or I will do it when it will be merged)

feat: implement native tempdir getter for Android and iOS

---

js/packages/components/chat/MultiMember.tsx
js/packages/components/chat/OneToOne.tsx
js/packages/components/chat/shared-components/Chat.tsx
js/packages/components/chat/shared-components/Message.tsx
js/packages/components/helpers.ts
js/packages/components/main/Home.tsx
js/packages/components/main/Search.tsx

Even though moment (library) is not performant, now we have the time formatters in one place, so it should be easier to swap out the library and/or tweak the display.

chore(messenger): unify date formatting

---

go/framework/bertybridge/bridge_protocol.go
go/internal/initutil/ipfs.go
go/internal/multipeer-connectivity-transport/conn.go
go/internal/multipeer-connectivity-transport/connmgr.go
go/internal/multipeer-connectivity-transport/discovery.go
go/internal/multipeer-connectivity-transport/driver/MCManager.m
go/internal/multipeer-connectivity-transport/driver/bridge_darwin.go
go/internal/multipeer-connectivity-transport/driver/bridge_unsupported.go
go/internal/multipeer-connectivity-transport/driver/mc-driver.h
go/internal/multipeer-connectivity-transport/driver/mc-driver.m
go/internal/multipeer-connectivity-transport/init.go
go/internal/multipeer-connectivity-transport/listener.go
go/internal/multipeer-connectivity-transport/transport.go
js/packages/berty-app/ios/Podfile.lock
js/packages/berty-app/ios/info.yaml

Stabilize MC: close connections when the driver lost the connection with the remote peer
Rename the transporter with a name more generic: in the future, we should reutilize the transporter for multiple drivers (BLE, Nearby)

fix: Improve MC stability

---

Makefile
js/Makefile
js/gen.sum

This allows to use `-jx` on the root Makefile for concurrent generation using `makeparallel` (just install the `makeparallel` package and then use `make generate -j12`).

build: Fix Makefiles to be compatible with jobserver.

---

js/Makefile
js/gen.sum
js/packages/components/chat/MultiMember.tsx
js/packages/components/chat/OneToOne.tsx
js/packages/components/chat/shared-components/Message.tsx

- creates a reusable wrapper for system messages with optional header logo:
**also**:
- removes some redundant build targets

chore(messenger): system message harmonization

---

Makefile
go.mod
go.sum
go/Makefile
go/cmd/bertydoctor/example_test.go
go/cmd/bertydoctor/main.go
go/cmd/bertydoctor/rdvp.go
go/gen.sum
go/internal/tinder/driver_rdv.go
tool/go.mod
tool/go.sum

Outputs like :
```
[+] OK     RDVP QmdT7AmhhnbuwvCpa5PH1ySK9HJVB82jr3fo1bxMxBPW6p:
[+] "/ip4/51.159.21.214/tcp/4040"
[-] "/ip4/51.159.21.214/udp/4040/quic": Error advertising on "/ip4/51.159.21.214/udp/4040/quic": failed to dial QmdT7AmhhnbuwvCpa5PH1ySK9HJVB82jr3fo1bxMxBPW6p: all dials failed
* [/ip4/51.159.21.214/udp/4040/quic] NO_ERROR: Handshake did not complete in time
[+] OK     RDVP 12D3KooWHhDBv6DJJ4XDWjzEXq6sVNEs6VuxsV1WyBBEhPENHzcZ:
[+] "/ip4/51.15.25.224/tcp/4040"
[-] "/ip4/51.15.25.224/udp/4040/quic": Error advertising on "/ip4/51.15.25.224/udp/4040/quic": failed to dial 12D3KooWHhDBv6DJJ4XDWjzEXq6sVNEs6VuxsV1WyBBEhPENHzcZ: all dials failed
* [/ip4/51.15.25.224/udp/4040/quic] NO_ERROR: Handshake did not complete in time
[-] WARN   RDVP …
```

feat: check for health of the RDVPs in `make doctor`

---

js/android/app/src/debug/AndroidManifest.xml
js/android/app/src/debug/res/values/strings.xml
js/android/app/src/releaseStaff/res/values/strings.xml
js/android/app/src/releaseYolo/res/values/strings.xml

- Remove network-security-config from debug variant to restore automatic binding between Android device/emulator and metro server
- Set different app name for each variant

fix: android flavors config for network security and app name

---

js/packages/berty-i18n/locale/debug/messages.json

this should hotfix the red ci on every PR
there is something weird, the "protobuf/genjs" check is not run on this PR although it's what was failing and is fixed here
(example of the problem fixed: https://github.com/berty/berty/runs/1351689324#step:12:31)
we should probably review the filters

chore: regen debug messages

---

.github/workflows/integration.yml

Currently if something fail the urlGen is skipped lefting a blank url

update integration, run url gen at first

---

.github/workflows/go.yml
go/cmd/berty-integration/main.go
go/cmd/berty-integration/main_unsupported.go

`github.com/zcalusic/sysinfo` calls unavailable syscalls on darwin.

fix: go's `make install` on darwin

---

.github/workflows/ios.yml

This fixes the `go build runtime/cgo: invalid flag in go:cgo_ldflag: -fembed-bitcode` error

fix(ci): downgrade go version in ios build

---

js/packages/berty-i18n/locale/en/messages.json
js/packages/components/onboarding/CreateAccount.js
js/packages/components/settings/DevTools.tsx
js/packages/store/context.ts
js/packages/store/provider.tsx
js/packages/store/providerEffects.ts
js/packages/store/providerReducer.ts

This is a quick fix for the flow bridge in js store
We have to use all methods from `accountService` instead of `GoBridge`
When we have a stream error, the restart button does not work (i've add a devtool button that simulate this error)

fix(messenger): flow bridge

---

go.mod
go.sum
js/Makefile
js/gen.sum
js/ios/.gitignore
js/ios/OpenSSL-Universal-Override.podspec
js/ios/Podfile
js/ios/Podfile.lock
js/ios/berty.yaml

**Note:** Overriding `OpenSSL-Universal` pod required by RN using a local podspec could break the project at some point (e.g if we update RN and RN update the `OpenSSL-Universal` version, we will need _at least_ to update the version in our local podspec).
I tried to find a way to remove a pod transitive dependency (which could lead to similar issue anyway), but due to lack of time, I used this solution instead.

feat: bind go-libtor deps with iOS app

---

go.mod
go.sum
js/Makefile
js/android/.gitignore
js/gen.sum
js/ios/.gitignore
js/metro.config.js

We waste a lot of time rebuilding the framework from scratch each time we modify two lines of go in the project (sometimes ten times a day).
I temporarily replace gomobile by my fork in the go.mod in order to take advantage of the cache. This replace will be removed when this [PR](https://github.com/golang/mobile/pull/58) will be merged or when someone else will have implemented this feature in gomobile. :)

feat: setup gomobile cache to reduce rebuild time

---

js/Makefile
js/gen.sum

fix: Makefile rule for tor deps download

---

js/Makefile

This PR temporarily removes embedTor from the iOS build until the Tor transport is fixed.

fix: temporary disable embedTor for iOS

---

.github/workflows/dependent-issues.yml

Hey there :wave:
This is to migrate this repo from using [DEP](https://github.com/apps/dep) bot to a new GitHub action:  [Dependent Issues]( https://github.com/marketplace/actions/dependent-issues). 
* The current DEP bot has _been deprecated and no longer works_.
* The new Action works the same way the bot did but with additional features/changes:
- Works with both _PRs and issues_ (disabled by default).
- Works with _cross-repository_ dependencies e.g. `microsoft/vscode#999`.
- It _notifies users by writing a comment_ with the list of dependencies and keep their states updated. This is especially useful when having the action enabled for non-PR issues.
- Keywords and the label _can now be customized._
- It sets the state of the head commit on a PR _to `pending` instead of `failure`_ …

chore(github): use Dependent Issues action

---

js/packages/go-bridge/defaults.ts
js/packages/go-bridge/types.ts
js/packages/store/providerEffects.ts

Logger filters must be given via grpc request to `openAccount` (https://github.com/berty/berty/blob/master/go/pkg/bertyaccount/service_account.go#L58)
The command line argument `--log.filters` is not used for mobiles.

fix: pass log filters through gobridge

---

go/pkg/bertymessenger/handlers.go

Signed-off-by: Norman Meier <norman@berty.tech>
Fixes https://github.com/berty/bugs/issues/191

fix(messenger): prevent overriding contact info with own info

---

.github/workflows/release.yml

Improves workflow run times by ~45s. Leverages changes here https://github.com/codfish/semantic-release-action/pull/156
See https://github.com/codfish/semantic-release-action/issues/142 for more context

ci: update semantic release action to pull from ghcr

---

.github/workflows/android.yml

Go1.15.8 is out
This reverts commit 2b1c93ec43d0e09909e0ab0d7694ec73dee230f7.
Continues #3018

Revert "fix: android build on CI with ndk22"

---

go/pkg/bertyprotocol/scenario_test.go
go/pkg/bertyprotocol/testing.go

fix: ConnectAll and ConnectInLine in scenario_test

---

go/cmd/berty/gui.go

Should help prevent issues like #3228 being open

chore(bergy): clearer usage description

---

docs/protocol/README.md

2 of the markdown links to rendezvous-point chapter (on line 96) were broken.
Sorry for the double commit. I closed #3251. Was not thinking clearly.
Hopefully this one should be signed correctly. 😄

chore: fix typo in docs/protocol/README.md

---

go/README.md
go/cmd/berty-integration/README.md
go/framework/bertybridge/blackbox_test.go
go/internal/initutil/ipfs.go
go/internal/initutil/logger.go
go/internal/initutil/manager.go
go/internal/initutil/node.go
js/packages/go-bridge/defaults.ts
tool/compose-integration/docker-compose.yml
tool/tyber/go/parser/header.go

- `p2p.bootstrap`: ipfs bootstrap node, `:default:` will set ipfs default bootstrap node
- `p2p.dht`: dht mode, can be: `client`, `server`, `auto`, `autoserver`,
- `p2p.dht-randomwalk`: if `true` dht will have dht randomwalk enable

feat: rework some flags

---

js/Makefile
js/android/app/build.gradle
js/android/gradle/wrapper/gradle-wrapper.properties
js/android/settings.gradle
js/package.json

This PR allows users who want to build the Android app to just click the "Run" button in Android Studio, without having to run a Makefile rule to build the deps.

feat: auto make app deps from gradle

---

js/packages/components/chat/ContactSettings.tsx
js/packages/components/chat/OneToOneSettings.tsx
js/packages/components/chat/common.tsx
js/packages/components/main/Scan.tsx

fix: android footer and status bar

---

js/ios/Gemfile
js/ios/Gemfile.lock

I'm not sure why this problem occurs but installing pods fails on a freshly reinstalled Macbook.
It should be a deps from cocoapods then, no idea why it doesn't install with it.
Error fixed:
```term
> make ios.release
(...)
Downloading dependencies
Installing BVLinearGradient (2.5.6)
Installing CocoaAsyncSocket (7.6.5)
(...)
Generating Pods project
LoadError - cannot load such file -- rexml/document
```

fix: rexml gem is missing when running project on a fresh install

---

js/packages/components/avatars.tsx

The problem existed from my previous PR pressable avatar. 
Error: useNavigation couldn't find 
Avatars were working fine in Chat view as Chat Views are inside NavigationStack. Avatars have also used in notification components, where it can't find useNavigation; but have to use navigationRef to navigate. I have fixed it.

fix: navigation crash issue

---

go/pkg/bertyaccount/service_account.go

fix: revert "use `initutil.New` in service_account"

---

go/pkg/bertymessenger/api.go
go/pkg/bertymessenger/db.go
go/pkg/bertymessenger/db_test.go
go/pkg/bertymessenger/service.go

bench using Interact on multiple node in parallel with a TestingInfra (aka sending messages in spam conditions)
```
nodes: 10
messagesPerNode: 300
messagesTotal: 3000
```
1513081f0a43a11f26998ec69bea678e9cc359d9 (master)
```
avg: 8m4.866547189s
min: 7m24.719786834s
max: 8m49.098070929s
avg/msg: 1.616221823s
min/msg: 1.482399289s
max/msg: 1.763660236s
```
9747980998f6ab69d6ce41eda7866750397b0297 (this branch)
```
avg: 2m29.030747214s
min: 2m20.090942079s
max: 2m35.32906842s
avg/msg: 496.769157ms
min/msg: 466.969806ms
max/msg: 517.763561ms
```
summary: more than 3 times faster without the lock

fix(messenger): remove useless locks

---

js/android/app/proguard-rules.pro

fix: prevent proguard to strip inAppBrowser required symbols

---

js/Makefile

fix: unset Android env var to prevent gomobile error on init

---

js/Makefile

Forgot to add this change in #3412 

fix: unset Android env var to prevent gomobile error on bind

---

go/internal/initutil/ipfs.go
js/packages/go-bridge/defaults.ts

Add `none` opt to `-p2p.dht` flag to disable ipfs routing (DHT)

feat: add none routing opt

---

go/internal/ble-driver/BleInterface_darwin.m
go/internal/ble-driver/BleManager_darwin.h
go/internal/ble-driver/BleManager_darwin.m
js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleDriver.java

* change BleManager singleton for non-ARC version (crashed when switching account)
* stop scanner timer in the main thread (crashed when stopping the node)
* Track correctly the broadcast receiver register status to avoid to unregister it multiple times (crashed when switching account)

fix: BLE crashes

---

go/cmd/berty/mini/view_group_incoming.go

Fixed a small grammatical error in Berty mini.
Before:
```
15:29:45 -------- peer joined <12D3KooWQg5mUwK> on: /ip4/147.75.195.153/udp/4001/quic/p2p/QmW9m57aiBDHA…
15:30:21 -------- peer leaved <12D3KooWQg5mUwK>
```
After
```
15:39:02 -------- peer joined <12D3KooWQg5mUwK> on: /ip4/192.168.1.86/tcp/37275
15:42:08 -------- peer left <12D3KooWMkpZWyW>
```
If necessary, I could add 2 spaces before the PeerId to line it up better. 
Signed-off-by: Mathis Van Eetvelde <mathis.vaneetvelde@protonmail.com>

chore: fix typo in berty mini

---

js/packages/components/main/home/Home.tsx

This fixes the black screen on account creation. Was due to a variable being interpreted as text outside of a Text component

fix: booleanize variable

---

go.mod
go.sum

properly closes the sql datastore and fixes possible config desync

fix: bump go-ipfs-repo-encrypted

---

js/packages/components/chat/MessageList.tsx

Loading of conversations is blocked if the last message is a MonitorMetadata
Fixes #3629

fix: ignore fake cids while finding lazy-loading ref

---

go/internal/tinder/service_test.go
go/pkg/bertyprotocol/api_push.go
go/pkg/bertyprotocol/api_replication.go

remove `InsecureSkipVerify` opt on grpc service

fix: remove InsecureSkipVerify

---

js/package.json
js/yarn.lock

chore: bump typescript to 4.4.4

---

.github/workflows/go.yml
go/Makefile
go/gen.sum
go/internal/testutil/skip.go
go/pkg/bertybot/bot_test.go
go/pkg/bertymessenger/service_test.go
go/pkg/bertyprotocol/account_export_test.go
go/pkg/bertyprotocol/scenario_test.go
go/pkg/bertyprotocol/store_message_test.go
go/pkg/bertyprotocol/store_metadata_test.go

* Rename Unstable to Flappy
* Bump go version on CI
* Fix various tests with invalid names (should contain Flappy if flappy)
* Set flappy tests as officially flappy in the tests

chore: rename Unstable to Flappy for testing utilities

---

js/ios/berty.yaml

we need to set this to false to avoid a `Validation Error` while submitting
the build to apple

fix: disalbe `embed_swift` for Notification Service

---

go.mod
go.sum

this contains a fix and optimization for prefix queries

fix: bump go-ipfs-repo-encrypted to v1.0.11

---

js/packages/components/chat/footer/ChatTextInput.tsx

Fix https://github.com/orgs/berty/projects/42#card-74695232

fix: cancel reply cross is outside box with long large text

---

.github/workflows/go.yml
go/.golangci.yml
go/cmd/berty/peers.go
go/cmd/rdvp/main.go
go/internal/grpcutil/lazy_client.go
go/internal/grpcutil/server.go
go/internal/initutil/ipfs.go
go/internal/omnisearch/config.go
go/pkg/bertymessenger/service.go
go/pkg/bertyprotocol/api_event.go
go/pkg/tyber/format.go

- update deprecated `golint` -> `revive`
- update deprecated `scopelint` -> `exportloopref`

feat: update deprecated golangci linters: golint/scopelint 

---

go/internal/ble-driver/BertyDevice_darwin.m
go/internal/ble-driver/BleInterface_darwin.m
go/internal/ble-driver/BleManager_darwin.m
go/internal/ble-driver/BleQueue.m
go/internal/ble-driver/CountDownLatch_darwin.h
go/internal/ble-driver/CountDownLatch_darwin.m
go/internal/ble-driver/PeerManager.m

Fix a crash when the iOS BLE driver is stopping.
Fix a stuck when the iOS BLE driver starts on simulators.

fix: crash when iOS BLE driver stops

---

go.mod
go.sum

final PR of sqlite datastore support upstream (started at https://github.com/ipfs/go-ds-sql/pull/21)

fix(go): bump encrepo

---

js/packages/components/chat/MessageList.tsx
js/packages/components/chat/message/UserMessage.tsx
js/packages/store/hooks.ts

- Scroll more natural on Android
- Spinner is displayed if messages are loading from Go
- Scrolling with finger on an other user’s message should work even if scrolled in diagonal
- Reply by scrolling right on an other user’s message should still work

fix: fix scroll problems on Android messages in conversations

---

js/packages/berty-i18n/locale/en-US/messages.json
js/packages/berty-i18n/locale/fr-FR/messages.json
js/packages/components/chat/EnableNotificationsButton.tsx
js/packages/components/chat/footer/ChatFooter.tsx
js/packages/components/chat/footer/file-uploads/AddFileMenu.tsx
js/packages/components/chat/footer/record/RecordComponent.tsx
js/packages/components/main/Permissions.tsx
js/packages/components/main/home/Home.tsx
js/packages/components/onboarding/AdvancedSettings.tsx
js/packages/components/onboarding/CreateAccount.tsx
js/packages/navigation/types.ts
js/packages/rnutil/checkPermissions.ts
js/packages/store/effectableCallbacks.ts

This PR makes the user navigate to a permission screen after pressing on gallery and camera chat footer buttons (after clicking on "+") if he doesn't have those permissions.
It could need a lottie file for gallery permission, camera lottie file is temporary used instead.
The behavior can still be: asking for permission without navigating to permissions screen.

fix: request camera and gallery permissions in chat menu footer

---

go/cmd/berty-integration/main.go
tool/compose-integration/Makefile
tool/compose-integration/docker-compose.yml

It's hard to say if this PR will solve integration random failed (~25% of time), but it will add more logs when it's the case
add some delays before running integration test and logs other containers when integration failed

chore: debug integration

---

Makefile

Self descriptive.
Produced with:
```bash
find . -type f | grep Makefile$ | grep -v ^./Makefile$ | cut -c 3- | while read f; do [[ -z $(grep -i clean ${f} | head -n1) ]] || echo -e "\t-cd $(dirname ${f}); \$(MAKE) clean"; done
```
So I'm confident to not have missed any sub `clean`.

build: add `clean` to the top-level `Makefile`

---

go/cmd/berty/mini/view_group.go

In `func (v *groupView) commandParser`, the prefix of a command like "/debug store group_pk metadata" is removed with:
strings.TrimPrefix(input, prefix+" ")
This is so that the `cmd` parameter for the command only has the args like "group_pk metadata" without the command prefix. But if the user simply enters "/debug store" then the call to `TrimPrefix` does not match. (There is no space after the prefix.) Therefore the `cmd` parameter for the command contains the prefix "/debug store". But `cmd` should be the empty string in this case. This commit changes to call `TrimPrefix` only with the prefix, and to trim the spaces after.
Signed-off-by: Jeff Thompson <jeff@thefirst.org>

fix: mini: Trim command spaces after TrimPrefix

---

js/README.md

With go 1.18, the instructions for `go get golang.org/x/mobile/cmd/gomobile/...` don't work anymore. But the Makefile already does gomobile init, right? On a fresh macOS, I am able to do make and run android.debug without explicitly doing gomobile init. So, remove the unneeded and outdated install instructions.
(If I'm wrong and it is necessary to do gomobile init, outside of running make, then we can close this pull request.)

fix: js: In README, remove unneeded/outdated gomobile install instructions

---

go/pkg/bertymessenger/api.go
go/pkg/bertyprotocol/api_push.go
js/packages/utils/notification/notif-push.ts

fix: push notifications

---

go/README.md
go/cmd/berty/mini.go

When I read "not fully compatible with the app" I thought that maybe they use different crypto protocols, or maybe I couldn't exchange contact invitations. But it is not that bad. This pull requests softens the message.

fix: go/mini: Clarify message for compatibility with the app.

---

Dockerfile

Hey frens!
This workflow change makes the Valist Publish dependent on the Release workflow instead of the GitHub Release event, since there are modifications to the release post-event.

fix: modify Valist workflow

---

README.md

The [Berty web page](https://berty.tech/) has links to install from Google Play and the App Store. But a user may first land on this README which only says how to compile. Add the same links to Google Play and the App Store if the user just wants to install.
Signed-off-by: jefft0 <jeff@thefirst.org>

chore(README.md): add links to Google Play and App Store.

---

go/pkg/bertybot/handlers.go

Currently, when we register a command on a bot, if we carry out this command, the space trailings will be taken into account as argument.
For example if I register the command /test which takes a parameter and displays it
If I execute the command **with a space at the end**: ``/test Mikael`` 
then I would have two arguments Mikael and a space.
This is problematic in case like for example my phone adds a space at the end of a sentence if there is no dot.
For this I propose that we remove the trailing space.
Here is a screenshot with an example :

chore(bot): remove trailing space in commands

---

tool/scw-funcs/ghrunners/.gitignore
tool/scw-funcs/ghrunners/Makefile
tool/scw-funcs/ghrunners/README.md
tool/scw-funcs/ghrunners/go.mod
tool/scw-funcs/ghrunners/handler.go
tool/scw-funcs/ghrunners/handler_test.go
tool/scw-funcs/ghrunners/package.json
tool/scw-funcs/ghrunners/serverless.yml

Deployed here: https://ghrunners-lambda.berty.io/
```json
{"total_count":3,"runners":[{"id":149,"name":"ci-macos-2.berty.io","os":"macOS","status":"online","busy":false,"labels":[{"id":5,"name":"self-hosted","type":"read-only"},{"id":6,"name":"macOS","type":"read-only"},{"id":7,"name":"ARM64","type":"read-only"},{"id":8,"name":"public","type":"custom"}]},{"id":150,"name":"ci-macos-1.berty.io","os":"macOS","status":"online","busy":false,"labels":[{"id":5,"name":"self-hosted","type":"read-only"},{"id":6,"name":"macOS","type":"read-only"},{"id":7,"name":"ARM64","type":"read-only"},{"id":8,"name":"public","type":"custom"}]},{"id":151,"name":"ci-macos-3.berty.io","os":"macOS","status":"online","busy":false,"labels":[{"id":5,"name":"self-hosted","type":"read-only"},{"id":6,"name":"macOS","type": …
```

chore(ci): add runners' lambda

---

js/Makefile

fix: delete Bertypush.xcframework in js Makefile clean rule

---

js/README.md

With Node 12.x installed (the default on Ubuntu 22.04), `make android.release` gives the following error. Due to the faker dependency, the minimum Node version should be 14.x.
`error @faker-js/faker@6.3.1: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.22.9"`
Signed-off-by: jefft0 <jeff@thefirst.org>

fix: js: In README, bump Node requirement to 14.x

---

go/pkg/bertyprotocol/group_context.go

This pull request has two commits. The first commit fixes some logic in `activateGroupContext` for printing log messages. Running `TestFlappyRestoreAccount` prints the log message "group_context.go:122 gc member public key device doesn't match". But the public key does match, so this commit changes to use `if !pk.Equals` [here](https://github.com/berty/berty/blob/master/go/pkg/bertyprotocol/group_context.go#L121), similar to the other log messages.
Also, the test prints "FillMessageKeysHolderUsingPreviousData took 373.982µs" . But this is the wrong value because the log message [is printed](https://github.com/berty/berty/blob/master/go/pkg/bertyprotocol/group_context.go#L144) immediately after the goroutine is started, not after the operation is completed. 
Also, the test prints …

Fix activateGroupContext logging

---

.github/dependabot.yml

Set 0 as `pull-request-limit` to only enable security update on dependabot.
see:
- https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
also, add a security tag on dependabot's pull request

fix(dependabot): disable version update (enable security update only)

---

.tool-versions

Add buf.build version in .tool-versions file because we need it for compiling JS proto.

chore: add buf to .tool-versions file

---

Makefile

Ref: https://stackoverflow.com/a/3411105
Small change I had to make to get the Makefile commands work on my machine (`/bin/sh` is symlinked to dash on my PopOS).
This should still work the same with bash.

make Makefile asdf target POSIX sh compatible

---

.tool-versions

chore: bump golangci lint to 1.51.2

---

Makefile

`make clean` doesn't found the the good berty mini path

fix: make clean

---

.github/workflows/ios.yml

When we run e2e CI tests, we try to run them with an iPhone 11 but with XCode 14, only iPhone 14 simulators are available by default.

fix: CI Runners with XCode 14.3

---

go/internal/accountutils/utils.go
go/internal/messengerdb/db.go
go/internal/messengerdb/db_test_utils.go

fixes error "database is locked", caused by concurrent access from deal goroutines to a single sqlite3 db connection 
see: https://github.com/mattn/go-sqlite3#:~:text=Error%3A%20database%20is%20locked 
see: https://github.com/filecoin-project/boost/pull/657
taken from: https://github.com/filecoin-project/boost/blob/main/db/db.go#L29-L31

fix: use SetMaxOpenConns to fix `database is locked` issue

---

go/cmd/berty/daemon.go
go/cmd/berty/directory_service.go
go/cmd/berty/main.go
go/cmd/berty/push.go
go/cmd/berty/replication.go
go/internal/initutil/manager.go
go/internal/initutil/manager_test.go
go/pkg/bertyaccount/service_account.go

properly handle close signal when berty run in daemon mode

fix: properly handle close signal on main

---

README.md
go/README.md

Change berty protocol to wesh protocol in readme's
Talked with @jefft0 and we came to the conclution that the link to the Berty Protocol package was not needed.
Signed-off-by: Luke Tenback (github@luke.irtl.nl)

removed the link to the bertyprotocol package

---

js/android/app/src/main/AndroidManifest.xml
js/android/build.gradle

To be allowed to upload Berty to the Play Store, we need to use at least the Android API 31.
With API 31, each Activity which has intent-filter must set android:exported="true" in the AndroidManifest.xml (see https://stackoverflow.com/questions/70333565/targeting-s-version-31-and-above-requires-that-an-explicit-value-for-android)

chore: update berty app to Android API 31

---

js/android/app/src/main/AndroidManifest.xml
js/android/app/src/main/java/tech/berty/gobridge/bledriver/BleDriver.java
js/android/build.gradle
js/android/gradle/wrapper/gradle-wrapper.properties
js/ios/Podfile.lock
js/package.json
js/packages/utils/permissions/permissions.ts
js/web/craco.config.js
js/web/package.json
js/web/yarn.lock
js/yarn.lock

Since Android 12, no more needs to ask for `ACCESS_FINE_LOCATION` to enable Bluetooth. Instead, we have to request 3 different Bluetooth permissions to the user: `BLUETOOTH_SCAN`, `BLUETOOTH_ADVERTISE`, and `BLUETOOTH_CONNECT`.
We have also to support Android API level 31 and above that introduces these new permissions.
fixes https://github.com/berty/berty/issues/4733
Tested on iPhone 7 and 8.
Tested on Android 13 and 10.

fix: Blueetooth permissions for Android devices and above

---

js/packages/screens/chat/Share/Share.tsx
js/packages/screens/chat/Share/__snapshots__/Share.test.tsx.snap

- Fix for long user names affect position of QR code
- Provides a better fit for long username on the share screen.
fix #4391

fix: Long user names affect position of QR code

---

go.mod
go.sum
go/pkg/errcode/error.go
go/pkg/errcode/error_test.go

This PR is base on the dependabot's PR https://github.com/berty/berty/pull/4774
Since gRPC 1.55.0 (https://github.com/grpc/grpc-go/releases/tag/v1.55.0), `status.Code` and `status.FromError` handle wrapped errors. That breaks some of the Berty tests because the `Code()` method should now unwrap errors.

Chore/upgrade grpc dep and fix Error tests

---

js/packages/screens/chat/Home/components/conversation/ConversationItem.tsx

This pull request fixes an issue with translation escaping unicode characters. I've added the "interpolation: { escapeValue: false }" to avoid escaping the unicode.
fix #4371

Fix translation escaping unicode chars

---

js/package.json
js/packages/components/inputs/medium/MediumInput.tsx
js/packages/screens/chat/CreateGroupAddMembers/__snapshots__/CreateGroupAddMembers.test.tsx.snap
js/packages/screens/chat/MultiMemberSettingsAddMembers/__snapshots__/MultiMemberSettingsAddMembers.test.tsx.snap

This pull request fixes the background color of the text input to match the Figma design. 
The screen background has already been fixed in another PR.
It also adds an additional yarn command for regenerating the snapshot files.
Fix #4390

chore: Fix text input background color and add additional help command

---

js/packages/i18n/locale/en-US/messages.json

This pull request fixes a missing translation in the `messages.json` file. The translation for the `delete-account` section was incomplete, and this PR adds the missing translation.
width="250"
src="https://github.com/berty/berty/assets/689440/96afba6d-a481-405e-bfe1-191b3f36a662" />
width="250"
src="https://github.com/berty/berty/assets/689440/c4283cc8-f206-4669-af5a-2ce1704896ac" />

Fix missing translation

---

js/packages/screens/onboarding/CustomModeSettings/CustomModeSettings.tsx
js/packages/screens/onboarding/CustomModeSettings/__snapshots__/CustomModeSettings.test.tsx.snap

This pull request fixes the issue with the info icons in Custom Mode that were not leading anywhere. 
The changes include hiding an unused button and adjusting the alignment and padding of the info icon. This resolves issue #4415.

Fix info icons in Custom Mode

---

js/packages/screens/account/SelectNode/__snapshots__/SelectNode.test.tsx.snap
js/packages/screens/chat/MultiMemberSettings/__snapshots__/MultiMemberSettings.test.tsx.snap
js/packages/screens/chat/Share/__snapshots__/Share.test.tsx.snap
js/packages/screens/onboarding/CustomModeSettings/__snapshots__/CustomModeSettings.test.tsx.snap
js/packages/screens/settings/AboutBerty/__snapshots__/AboutBerty.test.tsx.snap
js/packages/screens/settings/Accounts/__snapshots__/Accounts.test.tsx.snap
js/packages/screens/settings/Appearance/__snapshots__/Appearance.test.tsx.snap
js/packages/screens/settings/DevTools/__snapshots__/DevTools.test.tsx.snap
js/packages/screens/settings/Network/__snapshots__/Network.test.tsx.snap
js/packages/screens/settings/Notifications/__snapshots__/Notifications.test.tsx.snap
js/packages/screens/settings/SettingsHome/__snapshots__/SettingsHome.test.tsx.snap
js/packages/screens/settings/ThemeEditor/__snapshots__/ThemeEditor.test.tsx.snap

This pull request fixes the width style in multiple components to use flexShrink: 1 and width: "90%" instead of width: "75%". This ensures that the components are displayed correctly on different screen sizes.

Fix broken snapshot tests in PR #4761

---

js/README.md

Please check the updated install instructions

Updated Android Studio install instructions to include Chipmunk

---

Makefile

Fix the `make` default command on root folder that generates the following issue:

chore: adding missing library to web project

---

.tool-versions

This PR updates golang to version 1.23.2 that fixes an issue where running the binary `berty` fails (either by doing `go build` or `go install`).

chore: bump-golang-1.23.2

---

js/ios/Podfile.lock
js/packages/components/items/Text.priv.tsx
js/packages/screens/account/SelectNode/__snapshots__/SelectNode.test.tsx.snap
js/packages/screens/chat/MultiMemberSettings/__snapshots__/MultiMemberSettings.test.tsx.snap
js/packages/screens/chat/Share/__snapshots__/Share.test.tsx.snap
js/packages/screens/onboarding/CustomModeSettings/__snapshots__/CustomModeSettings.test.tsx.snap
js/packages/screens/settings/AboutBerty/__snapshots__/AboutBerty.test.tsx.snap
js/packages/screens/settings/Accounts/__snapshots__/Accounts.test.tsx.snap
js/packages/screens/settings/Appearance/__snapshots__/Appearance.test.tsx.snap
js/packages/screens/settings/DevTools/__snapshots__/DevTools.test.tsx.snap
js/packages/screens/settings/Network/__snapshots__/Network.test.tsx.snap
js/packages/screens/settings/Notifications/__snapshots__/Notifications.test.tsx.snap
js/packages/screens/settings/SettingsHome/__snapshots__/SettingsHome.test.tsx.snap
js/packages/screens/settings/ThemeEditor/__snapshots__/ThemeEditor.test.tsx.snap

Adjust the width of the container to prevent the toggle button from going out of the screen.
Fixes #4823

Fix toggle button positioning on profile screen

---

.github/workflows/utils/mac-runner-matrix-builder.js

Some Github Action workflow used `macos-12` which is now deprecated by Github.
This PR update the version to the latest (15).

chore: upgrade macos version on CI jobs

---

.tool-versions

Update to ruby 3.2.2 (same version as gnonative, etc.) Hopefully, this will fix the CI build on macOS 15. On my local macOS, `make tests` passes and Berty Messenger builds and runs on iOS simulator.

chore: .tool-versions: Update to ruby 3.2.2
